'use strict';
const token=document.querySelector('meta[name="app-token"]').content;
const $=id=>document.getElementById(id);
let current=null, pending=false, uploading=false, busy=false, creating=false, selected=new Set(), lastMessages='', previewRequest=0;
function node(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function error(e){$('error').hidden=!e;$('error').textContent=e?String(e.message||e):'';}
async function api(path,options={}){
  const headers={'X-Engineer-Token':token,...options.headers};
  if(options.body && typeof options.body==='object' && !(options.body instanceof ArrayBuffer)){options.body=JSON.stringify(options.body);headers['Content-Type']='application/json';}
  const response=await fetch(path,{...options,headers,cache:'no-store'});
  if(!response.ok){let message=`Ошибка ${response.status}`;try{message=(await response.json()).error||message;}catch{}throw new Error(message);}
  return response.headers.get('content-type').startsWith('application/json')?response.json():response;
}
function controls(){ document.querySelectorAll('nav .session').forEach(button=>{button.disabled=pending||uploading;});$('send').disabled=!current||pending||busy||uploading;$('upload').disabled=!current||uploading||pending;$('new-chat').disabled=creating||pending||uploading;$('prompt').disabled=!current;$('task-mode').disabled=pending||busy||uploading;$('evidence-save').disabled=!current||pending||uploading||!$('evidence-file').options.length; }
async function sessions(){const list=await api('/api/sessions');$('sessions').replaceChildren();for(const s of list){const b=node('button',s.title,s.id===current?'session active':'session');b.disabled=pending||uploading;b.onclick=()=>switchSession(s.id);$('sessions').append(b);}return list;}
async function switchSession(id){if(pending||uploading)return;closePreview();current=id;selected=new Set();lastMessages='';for(const field of ['evidence-quote','evidence-statement','evidence-page'])$(field).value='';error(null);controls();await refresh();await sessions();}
async function createSession(){if(creating||pending||uploading)return;creating=true;controls();try{const s=await api('/api/sessions',{method:'POST',body:{title:'Новый диалог'}});await switchSession(s.id);}catch(e){error(e);}finally{creating=false;controls();}}
function renderMessages(snap){const key=JSON.stringify(snap.messages);if(key===lastMessages)return;lastMessages=key;$('messages').replaceChildren();if(!snap.messages.length){const e=node('div',undefined,'empty');e.append(node('span','E','empty-symbol'),node('h2','Начните с задачи'),node('p','Опишите вопрос или прикрепите ТЗ. История останется доступна после перезапуска.'));$('messages').append(e);}if(snap.history_windowed)$('messages').append(node('p','Показаны последние 200 сообщений. Более ранние сохранены в локальной базе.','muted'));for(const m of snap.messages){const article=node('article',undefined,`message ${m.role}`);article.append(node('div',m.role==='user'?'ВЫ':'ENGINEER OS','label'),node('div',m.content,'message-body'));if(m.role==='assistant')article.append(node('small','Предварительный ответ · требуется проверка'));$('messages').append(article);} $('messages').scrollTop=$('messages').scrollHeight;}
async function download(f){try{const response=await api(`/api/files/${f.id}`);const url=URL.createObjectURL(await response.blob());const link=node('a');link.href=url;link.download=f.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}catch(e){error(e);}}
function renderFiles(files){$('files').replaceChildren();if(!files.length)$('files').append(node('p','Пока нет файлов','muted'));for(const f of files){const card=node('div',undefined,'file');const label=node('label');const check=node('input');check.type='checkbox';check.checked=selected.has(f.id);check.disabled=busy||pending;check.onchange=()=>check.checked?selected.add(f.id):selected.delete(f.id);label.append(check,node('span',f.name));const button=node('button','Скачать оригинал','text-button');button.onclick=()=>download(f);card.append(label,node('small',`${(f.size/1024/1024).toFixed(2)} МБ · ${f.extraction_status==='UNAVAILABLE'?'Текст недоступен':'Текст не проверен'}`),node('small',f.extraction_note),button);$('files').append(card);}}
function closePreview(){previewRequest++;$('source-viewer').hidden=true;$('source-image').removeAttribute('src');$('source-caption').textContent='';}
async function showPreview(r){const session=current,request=++previewRequest;$('source-viewer').hidden=false;$('source-image').removeAttribute('src');$('source-caption').textContent='Загружаем страницу…';try{const response=await api(`/api/sessions/${session}/evidence/${r.id}/preview`);if(response.headers.get('content-type')!=='image/png')throw new Error('Неверный формат просмотра');const bytes=await response.arrayBuffer();if(bytes.byteLength>10*1024*1024)throw new Error('Изображение превышает лимит');const url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Не удалось прочитать страницу'));reader.readAsDataURL(new Blob([new Uint8Array(bytes)],{type:'image/png'}));});if(request!==previewRequest||session!==current)return;$('source-image').src=url;$('source-caption').textContent=r.name+' · стр. '+r.page+' · '+(r.provenance?.status==='UNIQUE'?'Область цитаты':'Кандидатные области, расположение не подтверждено')+'. Подсветка не подтверждает инженерный вывод.';}catch(e){if(request===previewRequest&&session===current){closePreview();error(e);}}}
$('close-preview').onclick=closePreview;
function renderEvidence(snap){const select=$('evidence-file'),choice=select.value;select.replaceChildren();for(const f of snap.files){const option=node('option',f.name);option.value=f.id;select.append(option);}if(snap.files.some(f=>f.id===choice))select.value=choice;$('evidence-list').replaceChildren();for(const r of snap.evidence||[]){const card=node('article',undefined,'evidence-card');card.append(node('strong','UNVERIFIED · '+(r.source_match==='MATCH'?'цитата совпала':'цитата не проверена')),node('p',r.statement),node('blockquote',r.quote),node('small',r.name+(r.page?' · стр. '+r.page:'')+' · SHA256 '+r.source_sha256),node('p',r.verification_note));if(r.provenance){const p=r.provenance;const labels={UNIQUE:'Одно место',AMBIGUOUS:'Неоднозначное расположение',NOT_LOCATED:'Координаты не найдены',NOT_APPLICABLE:'PDF-координаты неприменимы'};card.append(node('p',labels[p.status]||p.status,'provenance-status'));for(const box of p.regions.slice(0,10))card.append(node('small',`Область: ${box.left.toFixed(2)}, ${box.top.toFixed(2)} → ${box.right.toFixed(2)}, ${box.bottom.toFixed(2)} pt`));if(p.coordinate_system)card.append(node('small','Координаты от верхнего левого угла страницы без поворота; поворот '+p.page_rotation+'°'));if(p.regions_total>10)card.append(node('small','Показаны первые 10 областей.'));card.append(node('p',r.document_validation?.status==='VALIDATED'?'Привязка цитаты проверена; содержание не подтверждено.':'Привязка к единственной области не подтверждена.'));}if(r.page&&r.name.toLowerCase().endsWith('.pdf')){const button=node('button','Посмотреть страницу','preview-button text-button');button.onclick=()=>showPreview(r);card.append(button);}$('evidence-list').append(card);}}
function renderJobs(jobs){$('jobs').replaceChildren();if(!jobs.length)$('jobs').append(node('p','Задачи появятся после отправки сообщения','muted'));const labels={QUEUED:'В очереди',RUNNING:'Модель отвечает',SUCCEEDED:'Ответ сохранён',FAILED:'Не выполнено'};for(const j of jobs.slice(0,10)){const card=node('div',undefined,`job ${j.state.toLowerCase()}`);card.append(node('strong',labels[j.state]||j.state),node('p',j.prompt.slice(0,100)));if(j.error)card.append(node('small',j.error));if(j.result?.core_plan){const plan=j.result.core_plan;const box=node('details',undefined,'core-plan');box.append(node('summary','План ENGINEER CORE · проверки не выполнены'));for(const p of plan.specialists)box.append(node('p',p.label+' · не выполнено'));box.append(node('strong','Оригиналы · не доказательства'));for(const f of plan.materials)box.append(node('p',f.name+' · SHA256: '+f.sha256+' · '+f.source_status));for(const missing of plan.missing)box.append(node('small','Требуется: '+missing));card.append(box);}if(j.result?.context_truncated)card.append(node('small','Контекст частичный: учтена только часть истории или файлов.'));$('jobs').append(card);}}
async function refresh(){if(!current)return;const id=current;const snap=await api(`/api/sessions/${id}`);if(id!==current)return;busy=snap.jobs.some(j=>j.state==='QUEUED'||j.state==='RUNNING');$('title').textContent=snap.session.title;renderMessages(snap);renderFiles(snap.files);renderEvidence(snap);renderJobs(snap.jobs);controls();}
async function status(){const data=await api('/api/status');$('model-status').textContent=`${data.model.model} · ${data.model.available?'модель доступна':'нет связи с моделью'}`;$('model-status').className=`connection ${data.model.available?'online':'offline'}`;$('model-status').title=data.model.note;}
$('new-chat').onclick=createSession;
$('composer').onsubmit=async event=>{event.preventDefault();if(pending||busy||uploading||!current)return;const text=$('prompt').value.trim();if(!text)return;pending=true;controls();error(null);try{await api(`/api/sessions/${current}/jobs`,{method:'POST',body:{prompt:text,file_ids:[...selected],mode:$('task-mode').value}});$('prompt').value='';await refresh();await sessions();}catch(e){error(e);}finally{pending=false;controls();}};
$('evidence-form').onsubmit=async event=>{event.preventDefault();if(pending||uploading||!current)return;const raw=$('evidence-page').value,page=raw===''?null:Number(raw);if(page!==null&&(!Number.isSafeInteger(page)||page<1)){error('Укажите целый номер страницы');return;}pending=true;controls();error(null);try{await api(`/api/sessions/${current}/evidence`,{method:'POST',body:{file_id:$('evidence-file').value,page,quote:$('evidence-quote').value,statement:$('evidence-statement').value}});$('evidence-quote').value='';$('evidence-statement').value='';await refresh();}catch(e){error(e);}finally{pending=false;controls();}};
$('upload').onchange=async()=>{const file=$('upload').files[0];if(!file||!current)return;const id=current;if(file.size>100*1024*1024){error('Файл превышает 100 МБ');$('upload').value='';return;}uploading=true;controls();error(null);try{const f=await api(`/api/sessions/${id}/files?name=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:await file.arrayBuffer()});if(id===current)selected.add(f.id);await refresh();}catch(e){error(e);}finally{uploading=false;$('upload').value='';controls();}};
async function poll(){try{await refresh();}catch(e){error(e);}setTimeout(poll,1500);}
async function pollStatus(){try{await status();}catch(e){$('model-status').textContent='Сервер недоступен';$('model-status').className='connection offline';}setTimeout(pollStatus,15000);}
(async()=>{try{const list=await sessions();if(list.length)await switchSession(list[0].id);else await createSession();}catch(e){error(e);}controls();poll();pollStatus();})();
