'use strict';
const token=document.querySelector('meta[name="app-token"]').content;
const $=id=>document.getElementById(id);
let current=null, pending=false, uploading=false, busy=false, creating=false, selected=new Set(), lastMessages='', previewRequest=0, reviewTarget=null, driveConfigured=false;
const extractionViews=new Map();
const analysisViews=new Map();
const requirementDrafts=new Map();
function node(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function error(e){$('error').hidden=!e;$('error').textContent=e?String(e.message||e):'';}
async function api(path,options={}){
  const headers={'X-Engineer-Token':token,...options.headers};
  if(options.body && typeof options.body==='object' && !(options.body instanceof ArrayBuffer)){options.body=JSON.stringify(options.body);headers['Content-Type']='application/json';}
  const response=await fetch(path,{...options,headers,cache:'no-store'});
  if(!response.ok){let message=`Ошибка ${response.status}`;try{message=(await response.json()).error||message;}catch{}throw new Error(message);}
  return response.headers.get('content-type').startsWith('application/json')?response.json():response;
}
function controls(){document.querySelectorAll('.extract-native,.extract-docling,.extract-resume,.analysis-resume').forEach(b=>b.disabled=busy||pending||uploading); $('drive-import').disabled=!driveConfigured||!current||pending||uploading||busy;$('drive-source').disabled=pending||uploading;$('drive-sha').disabled=pending||uploading;$('core-checks').hidden=$('task-mode').value==='CHAT';document.querySelectorAll('#core-checks input').forEach(c=>{c.disabled=pending||busy||uploading;});document.querySelectorAll('nav .session').forEach(button=>{button.disabled=pending||uploading;});$('send').disabled=!current||pending||busy||uploading;$('upload').disabled=!current||uploading||pending;$('new-chat').disabled=creating||pending||uploading;$('prompt').disabled=!current;$('task-mode').disabled=pending||busy||uploading;$('review-save').disabled=!reviewTarget||pending||uploading;document.querySelectorAll('.review-button').forEach(b=>b.disabled=pending||uploading);$('evidence-save').disabled=!current||pending||uploading||!$('evidence-file').options.length;$('tz-save').disabled=!current||pending||uploading;document.querySelectorAll('.requirement-save,.candidate-from-source').forEach(b=>b.disabled=pending||uploading); }
async function sessions(){const list=await api('/api/sessions');$('sessions').replaceChildren();for(const s of list){const b=node('button',s.title,s.id===current?'session active':'session');b.disabled=pending||uploading;b.onclick=()=>switchSession(s.id);$('sessions').append(b);}return list;}
async function switchSession(id){extractionViews.clear();analysisViews.clear();if(pending||uploading)return;closePreview();closeReview();requirementDrafts.clear();resetDomains();clearCandidateLocation();$('tz-text').value='';current=id;selected=new Set();lastMessages='';for(const field of ['evidence-quote','evidence-statement','evidence-page','drive-source','drive-sha'])$(field).value='';error(null);controls();await refresh();await sessions();}
async function createSession(){if(creating||pending||uploading)return;creating=true;controls();try{const s=await api('/api/sessions',{method:'POST',body:{title:'Новый диалог'}});await switchSession(s.id);}catch(e){error(e);}finally{creating=false;controls();}}
function renderMessages(snap){const key=JSON.stringify(snap.messages);if(key===lastMessages)return;lastMessages=key;$('messages').replaceChildren();if(!snap.messages.length){const e=node('div',undefined,'empty');e.append(node('span','E','empty-symbol'),node('h2','Начните с задачи'),node('p','Опишите вопрос или прикрепите ТЗ. История останется доступна после перезапуска.'));$('messages').append(e);}if(snap.history_windowed)$('messages').append(node('p','Показаны последние 200 сообщений. Более ранние сохранены в локальной базе.','muted'));for(const m of snap.messages){const article=node('article',undefined,`message ${m.role}`);article.append(node('div',m.role==='user'?'ВЫ':'ENGINEER OS','label'),node('div',m.content,'message-body'));if(m.role==='assistant')article.append(node('small','Предварительный ответ · требуется проверка'));$('messages').append(article);} $('messages').scrollTop=$('messages').scrollHeight;}
async function download(f){try{const response=await api(`/api/files/${f.id}`);const url=URL.createObjectURL(await response.blob());const link=node('a');link.href=url;link.download=f.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}catch(e){error(e);}}
function renderCoverage(c){const box=node('details',undefined,'coverage');box.append(node('summary','Покрытие извлечения'));if(!c||c.status==='UNKNOWN'){box.append(node('p','Покрытие неизвестно: прежняя запись или извлечение недоступно.'));}else if(c.method==='NATIVE_PDF'){box.append(node('p',`Native-текст: попытка ${c.attempted_pages}/${c.total_pages} страниц; текст найден на ${c.pages_with_text}; не обработано ${c.unattempted_pages}.`));if(c.pages_without_text?.length)box.append(node('p','Без native-текста: страницы '+c.pages_without_text.join(', ')+'. Это не доказывает отсутствие содержания.'));for(const r of c.page_records||[])box.append(node('small',`Страница ${r.page}: ${r.status==='NO_NATIVE_TEXT'?'native-текст не найден':r.status==='PARTIAL_TEXT'?'текст усечён':'кандидат текста'} · сохранено ${r.stored_chars}/${r.text_chars} символов.`));}else{box.append(node('p',`UTF-8: сохранено ${c.stored_chars}/${c.source_chars} символов. Страницы неприменимы.`));}const reasons={PAGE_LIMIT:'Лимит 20 страниц',CHAR_LIMIT:'Лимит символов',EXTRACTION_UNAVAILABLE:'Извлечение недоступно',LEGACY_UNKNOWN:'Старое извлечение без покрытия'};for(const reason of c?.stop_reasons||[])box.append(node('small',reasons[reason]||reason));box.append(node('small','Полнота документа не проверена. Таблицы и графика не проверены; OCR не выполнен.'));return box;}
async function extractionAction(path,body){if(!current||busy||pending||uploading)return;pending=true;controls();error(null);try{await api(path,{method:'POST',body});await refresh();await sessions();}catch(e){error(e);}finally{pending=false;controls();}}
function extractionButtons(f){const box=node('details',undefined,'advanced-document-actions');box.append(node('summary','Дополнительные действия с документом'));for(const [backend,label] of [['native','Все страницы · native без OCR'],['docling','Docling · OCR и таблицы']]){const button=node('button',label,'extract-'+backend+' text-button');button.disabled=busy||pending||uploading;button.onclick=()=>extractionAction(`/api/sessions/${current}/extraction`,{file_id:f.id,backend});box.append(button);}return box;}
async function extractionJournal(job,more=false,page=null){const session=current;try{let view=extractionViews.get(job.id)||{pages:[],has_more:false,text:null};if(page!==null){const r=await api(`/api/sessions/${session}/jobs/${job.id}/pages/${page}`);view.text={page,text:r.blocks.map(b=>b.text).join('\n')};}else{const r=await api(`/api/sessions/${session}/jobs/${job.id}/pages?offset=${more?view.pages.length:0}&limit=50`);view={pages:more?[...view.pages,...r.pages]:r.pages,has_more:r.has_more,text:view.text};}if(current!==session)return;extractionViews.set(job.id,view);await refresh();}catch(e){if(current===session)error(e);}}
function renderExtraction(card,job){const r=job.result?.extraction;const box=node('details',undefined,'extraction-run');box.append(node('summary','Извлечение PDF · '+(r?.backend||job.mode)),node('small','UNVERIFIED · полнота не проверена · FINAL AUDIT NOT_RUN'));if(r)box.append(node('p',`Обработано ${r.processed_pages}/${r.total_pages} · BLOCK ${r.blocked_pages} · ошибки ${r.failed_pages}`),node('p','OCR: '+r.ocr+(r.current_page?' · текущая страница '+r.current_page:'')));const journal=node('button','Журнал страниц / обновить','extraction-journal text-button');journal.onclick=()=>extractionJournal(job);box.append(journal);const view=extractionViews.get(job.id);if(view){for(const p of view.pages){const row=node('div');row.append(node('small',`Страница ${p.page} · ${p.execution} · ${p.status} · ${p.stored_chars} символов`));for(const limit of p.limitations)row.append(node('small',limit));const text=node('button','Текст страницы '+p.page,'extraction-page text-button');text.onclick=()=>extractionJournal(job,false,p.page);row.append(text);box.append(row);}if(view.has_more){const more=node('button','Ещё 50 страниц','text-button');more.onclick=()=>extractionJournal(job,true);box.append(more);}if(view.text)box.append(node('pre','Страница '+view.text.page+' · непроверенный текст\n'+view.text.text,'extraction-text'));}if(r&&!r.budget_exhausted&&(job.state==='FAILED'||r.failed_pages>0)&&job.state!=='RUNNING'&&job.state!=='QUEUED'){const button=node('button','Продолжить извлечение','extract-resume text-button');button.disabled=busy||pending||uploading;button.onclick=()=>extractionAction(`/api/sessions/${current}/jobs/${job.id}/resume`,{});box.append(button);}card.append(box);}
async function analysisDrafts(job,more=false){const session=current;try{const old=analysisViews.get(job.id)||[];const r=await api(`/api/sessions/${session}/jobs/${job.id}/analysis?offset=${more?old.length:0}&limit=50`);if(current!==session)return;analysisViews.set(job.id,more?[...old,...r.records]:r.records);await refresh();}catch(e){if(current===session)error(e);}}
function renderAnalysisResume(box,job,r){
 if(r.summary_input_clipped)box.append(node('small','При свёртке обрезано '+r.summary_omitted_chars+' символов черновиков. Полные черновики доступны в результатах по частям; сохранность деталей сводки не подтверждена.'));
 if(r.model_calls!==undefined)box.append(node('small','Вызовов модели: '+r.model_calls+' · время: '+Math.round(r.model_elapsed_seconds||0)+' с'+(r.model_elapsed_estimated?' (включает оценку прерванных вызовов)':'')+' · Повторно использовано: '+(r.calls_reused||0)));
 if(r.budget_exhausted)box.append(node('small','Бюджет анализа исчерпан; продолжение не сбрасывает лимиты.'));
 if(!r.resume_supported&&job.state==='FAILED')box.append(node('small','Идентичность модели не подтверждена; для повтора создайте новое задание.'));
 if(r.resume_supported&&!r.budget_exhausted&&(job.state==='FAILED'||(job.state==='SUCCEEDED'&&!r.all_batches_completed))){
  const resume=node('button','Продолжить анализ','analysis-resume text-button');resume.disabled=busy||pending||uploading;
  resume.onclick=()=>extractionAction(`/api/sessions/${current}/jobs/${job.id}/resume-analysis`,{});box.append(resume);
 }
}
function sourceLocation(ref){
 const l=ref.locator;if(!l)return 'стр. '+ref.page;
 const derived=l.scope==='DERIVED_DOCX_LOCATION'?'DOC→DOCX (привязка производная) · ':'';
 return derived+(l.cell?l.sheet+'!'+l.cell:l.kind==='paragraph'?'абзац '+l.paragraph:l.kind==='table_cell'?'таблица '+l.table+', строка '+l.row+', ячейка '+l.column:'элемент '+ref.logical_unit);
}
function renderAutomaticAnalysis(card,job){const r=job.result.document_analysis;const box=node('div',undefined,'automatic-analysis');const labels={PREPARING:'Обрабатываем документ',ANALYZING:'Анализируем документ по частям',SUMMARIZING:'Собираем итоговую сводку',COMPLETED:'Анализ частей завершён',PARTIAL:'Сохранена часть анализа'};box.append(node('strong',labels[r.stage]||r.stage));for(const s of r.sources){box.append(node('p',s.name+' · обработано '+(s.processed_units??s.processed_pages??'—')+'/'+(s.total_units??s.total_pages??'—')+(s.total_units!==undefined?' логических элементов; физические страницы неизвестны':' страниц')));if(s.blocked_pages||s.failed_pages){box.append(node('small','Есть непрочитанные или ограниченные части: '+(s.blocked_pages||0)+'. '+(s.unavailable_pages?.length?(s.total_units!==undefined?'Элементы: ':'Страницы: ')+s.unavailable_pages.join(', '):'')));}for(const reason of s.limitations||[])box.append(node('small',reason));}if(r.batches_total)box.append(node('p','Части анализа: '+r.batches_completed+'/'+r.batches_total));if(r.text_omitted)box.append(node('small','Из-за лимита передана часть текста документа.'));if(r.summary_compressed)box.append(node('small','Итог — сводка черновиков; подробные результаты по частям сохранены.'));box.append(node('small','Содержание и полнота требуют проверки; инженерное принятие отсутствует.'));const button=node('button','Результаты по частям','analysis-drafts text-button');button.onclick=()=>analysisDrafts(job);box.append(button);const records=analysisViews.get(job.id);if(records){for(const item of records){const part=node('details',undefined,'analysis-receipt');part.append(node('summary',(item.kind==='SOURCE_PART'?'Часть документа':'Сводка')+' · '+item.status));if(item.refs?.length)part.append(node('small','Места источника: '+item.refs.map(sourceLocation).join(', ')));for(const ref of item.refs||[]){const bind=node('button','Создать кандидата · '+sourceLocation(ref),'candidate-from-source text-button');bind.onclick=()=>candidateFromSource(ref);part.append(bind);}part.append(node('pre',item.text||item.error,'extraction-text'));box.append(part);}if(records.length&&records.length%50===0){const more=node('button','Ещё результаты','text-button');more.onclick=()=>analysisDrafts(job,true);box.append(more);}}renderAnalysisResume(box,job,r);card.append(box);}
function renderFiles(files){$('files').replaceChildren();if(!files.length)$('files').append(node('p','Пока нет файлов','muted'));for(const f of files){const card=node('div',undefined,'file');const label=node('label');const check=node('input');check.type='checkbox';check.checked=selected.has(f.id);check.disabled=busy||pending;check.onchange=()=>check.checked?selected.add(f.id):selected.delete(f.id);label.append(check,node('span',f.name));const button=node('button','Скачать оригинал','text-button');button.onclick=()=>download(f);if(f.source_metadata?.provider==='GOOGLE_DRIVE')card.append(node('small','Drive · ID '+f.source_metadata.drive_file_id+' · SHA256 '+f.sha256));card.append(label,node('small',`${(f.size/1024/1024).toFixed(2)} МБ · ${f.extraction_status==='UNAVAILABLE'?'Текст недоступен':'Текст не проверен'}`),node('small',f.extraction_note),renderCoverage(f.extraction_coverage),button);if(/\.(pdf|docx|xlsx|doc)$/i.test(f.name)){card.append(node('small','Документ обработается автоматически при отправке задачи.'));if(f.name.toLowerCase().endsWith('.pdf'))card.append(extractionButtons(f));}$('files').append(card);}}
function closePreview(){previewRequest++;$('source-viewer').hidden=true;$('source-image').removeAttribute('src');$('source-caption').textContent='';}
async function showPreview(r){const session=current,request=++previewRequest;$('source-viewer').hidden=false;$('source-image').removeAttribute('src');$('source-caption').textContent='Загружаем страницу…';try{const response=await api(`/api/sessions/${session}/evidence/${r.id}/preview`);if(response.headers.get('content-type')!=='image/png')throw new Error('Неверный формат просмотра');const bytes=await response.arrayBuffer();if(bytes.byteLength>10*1024*1024)throw new Error('Изображение превышает лимит');const url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Не удалось прочитать страницу'));reader.readAsDataURL(new Blob([new Uint8Array(bytes)],{type:'image/png'}));});if(request!==previewRequest||session!==current)return;$('source-image').src=url;$('source-caption').textContent=r.name+' · стр. '+r.page+' · '+(r.provenance?.status==='UNIQUE'?'Область цитаты':'Кандидатные области, расположение не подтверждено')+'. Подсветка не подтверждает инженерный вывод.';}catch(e){if(request===previewRequest&&session===current){closePreview();error(e);}}}
$('close-preview').onclick=closePreview;
const REVIEW_LABELS={SOURCE_CONFIRMED:'Цитата и место сверены (запись пользователя)',REJECTED:'Не соответствует источнику',NEEDS_DATA:'Нужны данные',NOT_REVIEWED:'Не проверено'};
function closeReview(){reviewTarget=null;$('review-panel').hidden=true;$('review-caption').textContent='';$('review-note').value='';$('review-decision').value='NEEDS_DATA';$('review-actor').value='Локальный пользователь';controls();}
function openReview(r){if(pending||uploading)return;const same=reviewTarget?.id===r.id&&reviewTarget?.session===current;reviewTarget={id:r.id,session:current,revision:r.review_revision||0};if(!same){$('review-note').value='';$('review-decision').value='NEEDS_DATA';$('review-actor').value='Локальный пользователь';}$('review-panel').hidden=false;$('review-caption').textContent=r.name+(r.page?' · стр. '+r.page:'')+' · '+r.quote+' · SHA256 '+r.source_sha256;const pdf=r.name.toLowerCase().endsWith('.pdf');$('review-decision').querySelector('[value="SOURCE_CONFIRMED"]').disabled=r.source_match!=='MATCH'||r.source_confirmable===false||(pdf&&r.provenance?.status!=='UNIQUE');controls();}
$('close-review').onclick=closeReview;
$('review-form').onsubmit=async event=>{event.preventDefault();if(!reviewTarget||pending||uploading)return;const target={...reviewTarget};pending=true;controls();error(null);try{await api(`/api/sessions/${target.session}/evidence/${target.id}/reviews`,{method:'POST',body:{expected_revision:target.revision,decision:$('review-decision').value,note:$('review-note').value,actor:$('review-actor').value}});closeReview();await refresh();}catch(e){error(e);await refresh();}finally{pending=false;controls();}};
function renderEvidence(snap){const select=$('evidence-file'),choice=select.value;select.replaceChildren();for(const f of snap.files){const option=node('option',f.name);option.value=f.id;select.append(option);}if(snap.files.some(f=>f.id===choice))select.value=choice;$('evidence-list').replaceChildren();for(const r of snap.evidence||[]){const card=node('article',undefined,'evidence-card');card.append(node('strong','UNVERIFIED · '+(r.source_match==='MATCH'?'цитата совпала':'цитата не проверена')),node('p',r.statement),node('blockquote',r.quote),node('small',r.name+(r.page?' · стр. '+r.page:'')+' · SHA256 '+r.source_sha256),node('p',r.verification_note));if(r.locator)card.append(node('p',sourceLocation(r),'logical-location'));card.append(node('small','Тип данных: '+r.data_class+' · заявлен пользователем, не проверен'));for(const limit of r.source_binding?.limitations||[])card.append(node('small',limit));if(r.provenance){const p=r.provenance;const labels={UNIQUE:'Одно место',AMBIGUOUS:'Неоднозначное расположение',NOT_LOCATED:'Координаты не найдены',NOT_APPLICABLE:'PDF-координаты неприменимы'};card.append(node('p',labels[p.status]||p.status,'provenance-status'));for(const box of p.regions.slice(0,10))card.append(node('small',`Область: ${box.left.toFixed(2)}, ${box.top.toFixed(2)} → ${box.right.toFixed(2)}, ${box.bottom.toFixed(2)} pt`));if(p.coordinate_system)card.append(node('small','Координаты от верхнего левого угла страницы без поворота; поворот '+p.page_rotation+'°'));if(p.regions_total>10)card.append(node('small','Показаны первые 10 областей.'));card.append(node('p',r.document_validation?.status==='VALIDATED'?'Привязка цитаты проверена; содержание не подтверждено.':'Привязка к единственной области не подтверждена.'));}if(r.page&&r.name.toLowerCase().endsWith('.pdf')){const button=node('button','Посмотреть страницу','preview-button text-button');button.onclick=()=>showPreview(r);card.append(button);}const reviewButton=node('button','Проверить источник','review-button text-button');reviewButton.onclick=()=>openReview(r);card.append(reviewButton);if(r.reviews?.length){const history=node('details',undefined,'review-history');history.append(node('summary',`История решений · ${r.reviews.length}`));for(const e of r.reviews)history.append(node('p',`#${e.revision} · ${REVIEW_LABELS[e.decision]||e.decision} · ${e.actor} · ${new Date(e.created*1000).toLocaleString()}`),node('p',e.note));history.append(node('small','Подпись указана пользователем; инженерное принятие отсутствует.'));card.append(history);}$('evidence-list').append(card);}}
function renderCoreRun(card,job){const run=job.result.core_run;const box=node('details',undefined,'core-run');box.append(node('summary','Профильный анализ · '+run.status),node('small','Предварительные результаты · не доказательства · FINAL AUDIT NOT_RUN'));if(!run.analysis_complete)box.append(node('p',job.state==='FAILED'?'Выполнение остановлено. Сохранена часть результатов.':'Анализ выполняется; результаты сохраняются по ролям.'));const execution={NOT_RUN:'Не выполнено',RUNNING:'Выполняется',COMPLETED:'Черновик сохранён',FAILED:'Ошибка выполнения',INTERRUPTED:'Прервано'};for(const r of run.results){const row=node('article',undefined,'role-result');row.append(node('strong',r.label+' · '+(job.state==='FAILED'&&r.execution==='RUNNING'?'Прервано':execution[r.execution]||r.execution)+' · '+r.status));if(r.summary)row.append(node('p',r.summary));for(const f of r.findings){row.append(node('blockquote',f.text));if(f.source_ids.length)row.append(node('small','Непроверенные ссылки: '+f.source_ids.join(', ')));}for(const gate of r.finding_gates||[]){const detail=node('details',undefined,'finding-gate');detail.append(node('summary','Проверка основания · '+gate.status+' · '+gate.traceability),node('small',gate.reasons.join(', ')));for(const source of gate.sources)detail.append(node('blockquote',source.quote),node('small',source.data_class+' · '+(source.locator?sourceLocation(source):'стр. '+(source.page??'неприменимо'))+' · '+source.status));row.append(detail);}for(const limit of r.limitations)row.append(node('p','Ограничение: '+limit,'muted'));box.append(row);}card.append(box);}
function renderSpecialistChecks(card,report){if(!report.checks.length)return;const labels={NORMATIVE_DOCUMENT_NOT_VERIFIED:'Документ нормы не подтверждён',NORMATIVE_EDITION_NOT_VERIFIED:'Редакция нормы не подтверждена',NORMATIVE_SCOPE_NOT_VERIFIED:'Применимость нормы не подтверждена',NORMATIVE_CLAUSE_NOT_VERIFIED:'Пункт нормы не подтверждён',ACTUAL_CONDITION_NOT_VERIFIED:'Фактическое состояние не подтверждено',NORMATIVE_COMPARISON_NOT_VERIFIED:'Сопоставление с нормой не выполнено',CALCULATION_ARTIFACT_ROLES_NOT_BOUND:'Роли расчётных исходников не назначены',CALCULATION_SEMANTICS_NOT_VERIFIED:'Содержание расчётной модели не проверено',SOLVER_NOT_RUN:'Решатель не запускался'};const box=node('details',undefined,'specialist-checks');box.append(node('summary','Предметные проверки · '+report.status),node('small','Снимок задания · блокировка инженерного вывода, не доказанный дефект объекта'));for(const check of report.checks){box.append(node('strong',check.label+' · '+check.status),node('p',check.note));for(const reason of check.reasons)box.append(node('p',labels[reason]||reason));if(check.missing_roles?.length)box.append(node('small','Не подтверждены разделы комплекта: '+check.missing_roles.join(', ')));}box.append(node('small','Инженерное принятие отсутствует · FINAL AUDIT NOT_RUN'));card.append(box);}
function renderJobs(jobs){$('jobs').replaceChildren();if(!jobs.length)$('jobs').append(node('p','Задачи появятся после отправки сообщения','muted'));const labels={QUEUED:'В очереди',RUNNING:'Модель отвечает',SUCCEEDED:'Ответ сохранён',FAILED:'Не выполнено'};for(const j of jobs.slice(0,10)){const card=node('div',undefined,`job ${j.state.toLowerCase()}`);card.append(node('strong',j.mode.startsWith('EXTRACT_')?(j.state==='RUNNING'?'Извлечение выполняется':j.state==='SUCCEEDED'?'Цикл извлечения завершён':labels[j.state]):j.mode==='CORE_RUN'&&j.state==='SUCCEEDED'?'Результаты сохранены':labels[j.state]||j.state),node('p',j.prompt.slice(0,100)));if(j.result?.document_analysis)renderAutomaticAnalysis(card,j);if(j.mode.startsWith('EXTRACT_'))renderExtraction(card,j);if(j.error)card.append(node('small',j.error));if(j.result?.core_plan){const plan=j.result.core_plan;const box=node('details',undefined,'core-plan');box.append(node('summary',j.result.core_run?'План ENGINEER CORE · этап подготовки':'План ENGINEER CORE · проверки не выполнены'));for(const p of plan.specialists)box.append(node('p',p.label+(j.result.core_run?' · запланировано':' · не выполнено')));box.append(node('strong','Оригиналы · не доказательства'));for(const f of plan.materials)box.append(node('p',f.name+' · SHA256: '+f.sha256+' · '+f.source_status),renderCoverage(f.extraction_coverage));if(plan.source_reviews){box.append(node('strong','Проверки источников · не инженерное принятие'));for(const r of plan.source_reviews.candidates)box.append(node('p',r.candidate_id+' · '+(REVIEW_LABELS[r.decision]||r.decision)));if(plan.source_reviews.truncated)box.append(node('small','Показана часть кандидатов.'));}for(const missing of plan.missing)box.append(node('small','Требуется: '+missing));card.append(box);}if(j.result?.specialist_checks)renderSpecialistChecks(card,j.result.specialist_checks);if(j.result?.core_run)renderCoreRun(card,j);if(j.result?.requirements_report){const report=j.result.requirements_report;const box=node('details',undefined,'job-requirements');box.append(node('summary','Требования ТЗ · снимок анализа'));for(const r of report.requirements)box.append(node('p',r.text+' · '+r.status+' · '+r.traceability),node('small',r.reasons.join(', ')));box.append(node('small','Статус на момент задания. Актуальная проверка — в перечне требований ТЗ. Инженерное принятие отсутствует.'));card.append(box);}if(j.result?.context_truncated)card.append(node('small','Контекст частичный: учтена только часть истории или файлов.'));$('jobs').append(card);}}
async function refresh(){if(!current)return;const id=current;const [snap,tz,domains,realCase]=await Promise.all([api(`/api/sessions/${id}`),api(`/api/sessions/${id}/requirements`),api(`/api/sessions/${id}/domain-packets`),api(`/api/sessions/${id}/real-case`)]);if(id!==current)return;busy=snap.jobs.some(j=>j.state==='QUEUED'||j.state==='RUNNING');$('title').textContent=snap.session.title;renderMessages(snap);renderFiles(snap.files);renderEvidence(snap);renderRequirements(tz,snap.evidence||[]);renderDomains(domains,snap.evidence||[]);renderRealCase(realCase,snap.jobs);renderJobs(snap.jobs);controls();}
async function status(){const [data,drive]=await Promise.all([api('/api/status'),api('/api/drive/status')]);driveConfigured=drive.configured;$('drive-status').textContent=drive.note;controls();$('model-status').textContent=`${data.model.model} · ${data.model.available?'модель доступна':'нет связи с моделью'}`;$('model-status').className=`connection ${data.model.available?'online':'offline'}`;$('model-status').title=data.model.note;}
$('new-chat').onclick=createSession;
$('task-mode').onchange=controls;
$('composer').onsubmit=async event=>{event.preventDefault();if(pending||busy||uploading||!current)return;const text=$('prompt').value.trim();if(!text)return;pending=true;controls();error(null);try{await api(`/api/sessions/${current}/jobs`,{method:'POST',body:{prompt:text,file_ids:[...selected],mode:$('task-mode').value,...($('task-mode').value==='CHAT'?{}:{requested_checks:[...document.querySelectorAll('#core-checks input:checked')].map(c=>c.value)})}});$('prompt').value='';await refresh();await sessions();}catch(e){error(e);}finally{pending=false;controls();}};
$('evidence-form').onsubmit=async event=>{event.preventDefault();if(pending||uploading||!current)return;const raw=$('evidence-page').value,page=raw===''?null:Number(raw);if(page!==null&&(!Number.isSafeInteger(page)||page<1)){error('Укажите целый номер страницы');return;}pending=true;controls();error(null);try{await api(`/api/sessions/${current}/evidence`,{method:'POST',body:{file_id:$('evidence-file').value,page,quote:$('evidence-quote').value,statement:$('evidence-statement').value,data_class:$('evidence-class').value,source_job:$('evidence-source-job').value||null,logical_unit:$('evidence-unit').value?Number($('evidence-unit').value):null}});$('evidence-quote').value='';$('evidence-statement').value='';await refresh();}catch(e){error(e);}finally{pending=false;controls();}};
$('drive-form').onsubmit=async event=>{event.preventDefault();if(!driveConfigured||!current||pending||uploading||busy)return;const id=current;uploading=true;controls();error(null);try{const f=await api(`/api/sessions/${id}/drive-import`,{method:'POST',body:{source:$('drive-source').value,expected_sha256:$('drive-sha').value||null}});if(id===current){selected.add(f.id);$('drive-source').value='';$('drive-sha').value='';}await refresh();}catch(e){error(e);}finally{uploading=false;controls();}};
$('upload').onchange=async()=>{const file=$('upload').files[0];if(!file||!current)return;const id=current;if(file.size>100*1024*1024){error('Файл превышает 100 МБ');$('upload').value='';return;}uploading=true;controls();error(null);try{const f=await api(`/api/sessions/${id}/files?name=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:await file.arrayBuffer()});if(id===current)selected.add(f.id);await refresh();}catch(e){error(e);}finally{uploading=false;$('upload').value='';controls();}};
async function poll(){try{await refresh();}catch(e){error(e);}setTimeout(poll,1500);}
async function pollStatus(){try{await status();}catch(e){$('model-status').textContent='Сервер недоступен';$('model-status').className='connection offline';}setTimeout(pollStatus,15000);}
function clearCandidateLocation(){$('evidence-source-job').value='';$('evidence-unit').value='';$('evidence-location-label').textContent='Для Office выберите место в результатах по частям.';}
$('evidence-file').onchange=clearCandidateLocation;
async function candidateFromSource(ref){
 if(pending||uploading)return;const session=current;pending=true;controls();error(null);
 try{const record=await api(`/api/sessions/${session}/jobs/${ref.source_job}/pages/${ref.logical_unit??ref.page}`);if(session!==current)return;
  $('evidence-file').value=ref.file_id;$('evidence-page').value=ref.page||'';$('evidence-source-job').value=ref.locator?ref.source_job:'';$('evidence-unit').value=ref.logical_unit||'';
  $('evidence-location-label').textContent=sourceLocation(ref);$('evidence-quote').value=record.blocks.map(b=>b.text).join('\n').slice(ref.start,ref.end).slice(0,4000);$('evidence-statement').value='';$('evidence-class').value='U';
  $('evidence-form').closest('details').open=true;
 }catch(e){error(e);}finally{pending=false;controls();}
}
$('tz-form').onsubmit=async event=>{event.preventDefault();if(!current||pending||uploading)return;const session=current;pending=true;controls();error(null);try{await api(`/api/sessions/${session}/requirements`,{method:'POST',body:{text:$('tz-text').value}});$('tz-text').value='';requirementDrafts.clear();await refresh();}catch(e){error(e);}finally{pending=false;controls();}};
function renderRequirements(report,candidates){
 const active=document.activeElement,activeCard=active?.closest('.requirement-card'),focus=activeCard?{key:activeCard.dataset.key,kind:active.className,start:active.selectionStart,end:active.selectionEnd,value:active.value}:null;
 const expanded=new Map([...$('tz-list').querySelectorAll('.requirement-card')].map(c=>[c.dataset.key,c.querySelector('details')?.open]));
 $('tz-status').textContent=report.set_id?`Требования: ${report.requirements.length} · версия ${report.set_versions} · ${report.status} · инженерное принятие отсутствует`:'Перечень требований пока не составлен.';
 $('tz-list').replaceChildren();
 for(const row of report.requirements){
  const session=current,key=report.set_id+':'+row.id,draft=requirementDrafts.get(key),card=node('article',undefined,'requirement-card');
  card.dataset.key=key;
  card.append(node('strong',row.text),node('p',row.status+' · '+row.traceability),node('small',row.reasons.join(', ')));
  if(row.conclusion)card.append(node('p',row.conclusion));
  for(const source of row.sources)card.append(node('blockquote',source.quote),node('small',source.status+' · '+source.data_class+' · '+(source.locator?sourceLocation(source):'стр. '+(source.page??'неприменимо'))+' · '+source.reasons.join(', ')));
  const form=node('form'),conclusion=node('textarea'),relation=node('select'),choices=node('div');conclusion.className='requirement-conclusion';conclusion.required=true;conclusion.maxLength=2000;conclusion.setAttribute('aria-label','Вывод по требованию');conclusion.value=draft?.conclusion??row.conclusion??'';
  relation.className='requirement-relation';relation.setAttribute('aria-label','Связь с источниками');for(const [value,label] of [['SUPPORTS','Источник поддерживает вывод (заявлено)'],['CONTRADICTS','Противоречие (заявлено)'],['UNKNOWN','Связь не установлена']]){const option=node('option',label);option.value=value;relation.append(option);}relation.value=draft?.relation??row.relation;
  for(const c of candidates){const label=node('label',c.statement+' · '+c.name),check=node('input');check.type='checkbox';check.value=c.id;check.checked=(draft?.evidence_ids??row.sources.map(s=>s.candidate_id)).includes(c.id);label.prepend(check);choices.append(label);}
  const button=node('button','Сохранить связь и вывод','requirement-save primary');button.type='submit';form.append(conclusion,relation,choices,button);
  const revision=draft?.revision??row.revision;
  form.oninput=()=>requirementDrafts.set(key,{conclusion:conclusion.value,relation:relation.value,evidence_ids:[...choices.querySelectorAll('input:checked')].map(c=>c.value),revision});
  form.onchange=form.oninput;
  form.onsubmit=async event=>{event.preventDefault();if(pending||uploading||session!==current)return;pending=true;controls();error(null);try{await api(`/api/sessions/${session}/requirements/${row.id}/assessments`,{method:'POST',body:{set_id:report.set_id,expected_revision:revision,conclusion:conclusion.value,relation:relation.value,evidence_ids:[...choices.querySelectorAll('input:checked')].map(c=>c.value)}});requirementDrafts.delete(key);await refresh();}catch(e){error(e);}finally{pending=false;controls();}};
  if(row.history.length){const history=node('details');history.open=expanded.get(key)||false;history.append(node('summary','История выводов · '+row.history.length));for(const event of row.history)history.append(node('p','#'+event.revision+' · '+event.relation+' · '+event.conclusion));card.append(history);}
  card.append(form);$('tz-list').append(card);
 }
 if(focus){const card=[...$('tz-list').querySelectorAll('.requirement-card')].find(c=>c.dataset.key===focus.key);const target=card&&[...card.querySelectorAll('textarea,select,input,button')].find(e=>e.className===focus.kind&&(e.tagName!=='INPUT'||e.value===focus.value));if(target){target.focus({preventScroll:true});if(typeof focus.start==='number'&&target.setSelectionRange)target.setSelectionRange(focus.start,focus.end);}}
}
(async()=>{try{const list=await sessions();if(list.length)await switchSession(list[0].id);else await createSession();}catch(e){error(e);}controls();poll();pollStatus();})();

// Domain forms are kept mounted: polling never replaces an unsaved input.
let domainRevision=0,domainOptionsKey='';
const domainDraftRevisions=new Map();
const domainPanel=node('details',undefined,'domain-panel');
domainPanel.append(node('summary','Нормы и расчётные исходники'),node('p','Заполните цепочку нормы или назначьте роли исходникам. Это пользовательские сведения; достоверность нормы, факта и расчёта проверяется отдельно.'));
const domainStatus=node('p');const domainResults=node('div');domainPanel.append(domainStatus);
function domainInput(form,label,name,textarea=false){const box=node('label',label);const input=node(textarea?'textarea':'input');input.name=name;input.maxLength=1000;input.required=true;box.append(input);form.append(box);return input;}
function domainSelect(form,label,name){const box=node('label',label);const select=node('select');select.name=name;select.className='domain-source-select';box.append(select);form.append(box);return select;}
const normativeForm=node('form');normativeForm.id='normative-packet-form';normativeForm.append(node('h3','Нормативная цепочка'));
const chainLabels={document:'Документ',edition:'Редакция',scope:'Область применения и её основание',clause:'Пункт',requirement:'Требование: точный фрагмент цитаты',actual_condition:'Фактическое состояние: точный фрагмент цитаты',comparison:'Сопоставление',conclusion:'Предварительный вывод'};
const chainInputs={};for(const [key,label] of Object.entries(chainLabels))chainInputs[key]=domainInput(normativeForm,label,key,true);
const normSource=domainSelect(normativeForm,'Кандидат с текстом нормы','norm-source');normSource.required=true;
const actualSource=domainSelect(normativeForm,'Кандидат фактических данных','actual-source');actualSource.required=true;
const quantityToggle=node('input');quantityToggle.type='checkbox';const toggleLabel=node('label','Добавить числовое сопоставление');toggleLabel.append(quantityToggle);normativeForm.append(toggleLabel);
const quantityInputs={};for(const kind of ['actual','limit'])for(const field of ['value','unit','fragment']){const labels={value:'Значение',unit:'Единица как в цитате (м, мм, кН, МПа и др.)',fragment:'Точный фрагмент: число вместе с единицей'};const input=domainInput(normativeForm,(kind==='actual'?'Факт: ':'Требование: ')+labels[field],kind+'-'+field);input.maxLength=120;input.disabled=true;quantityInputs[kind+'-'+field]=input;}
const operator=domainSelect(normativeForm,'Оператор сравнения','operator');operator.className='';for(const value of ['<=','<','>=','>','==']){const o=node('option',value);o.value=value;operator.append(o);}operator.disabled=true;
quantityToggle.onchange=()=>{for(const input of Object.values(quantityInputs))input.disabled=!quantityToggle.checked;operator.disabled=!quantityToggle.checked;};
const normButton=node('button','Сохранить нормативный пакет');normButton.type='submit';normativeForm.append(normButton);
const calculationForm=node('form');calculationForm.id='calculation-packet-form';calculationForm.append(node('h3','Роли расчётных исходников'),node('p','Выберите цитату из файла для каждого доступного раздела. Отсутствующие разделы останутся видимыми. Наличие всех разделов не означает проверенный расчёт.'));
const calcLabels={MODEL:'Модель',GEOMETRY:'Геометрия',MATERIALS_SECTIONS:'Материалы и сечения',LOADS_COMBINATIONS:'Нагрузки и сочетания',SUPPORTS_RELEASES:'Опоры и освобождения',UNITS:'Единицы',SOLVER_LOG:'Протокол решателя',RESULTS:'Результаты',ACTUAL_STRUCTURE_REFERENCE:'Связь с реальной конструкцией'};
const calcSelects={};for(const [role,label] of Object.entries(calcLabels)){const select=domainSelect(calculationForm,label,role);select.dataset.domainRole=role;calcSelects[role]=select;}
const calcButton=node('button','Сохранить расчётный комплект');calcButton.type='submit';calculationForm.append(calcButton);
const advancedDomainForm=node('form');advancedDomainForm.id='advanced-domain-packet-form';
advancedDomainForm.append(node('h3','Расширенный проверяемый пакет'),node('p','Для adapter/solver receipts и завершённых проверок пункта 6. JSON проходит те же строгие серверные гейты; импорт не означает ACCEPTED.'));
const advancedDomainJson=node('textarea');advancedDomainJson.maxLength=32000;advancedDomainJson.required=true;advancedDomainJson.setAttribute('aria-label','JSON расширенного предметного пакета');advancedDomainJson.placeholder='{"kind":"CALCULATION",...}';advancedDomainForm.append(advancedDomainJson);
const advancedButton=node('button','Проверить и сохранить расширенный пакет');advancedButton.type='submit';advancedDomainForm.append(advancedButton);
domainPanel.append(normativeForm,calculationForm,advancedDomainForm,domainResults);$('tz-list').parentElement.after(domainPanel);
let realCaseRevision=0;
const realCasePanel=node('details',undefined,'real-case-panel');realCasePanel.id='real-case-panel';
realCasePanel.append(node('summary','Пункт 7 · полный реальный инженерный кейс'),node('p','Снимок объединяет ТЗ, оригиналы, evidence, предметные пакеты и результаты CORE_RUN. Он не выполняет FINAL AUDIT и не снимает BLOCK пункта 6.'));
const realCaseForm=node('form');realCaseForm.id='real-case-form';
const realCaseJob=node('select');realCaseJob.required=true;realCaseJob.setAttribute('aria-label','CORE_RUN для реального кейса');
const realCaseManifest=node('textarea');realCaseManifest.maxLength=12000;realCaseManifest.setAttribute('aria-label','JSON ролей исходников реального кейса');realCaseManifest.placeholder='{"TOR":["file-id"],"REPORT":["file-id"],"MODEL":["file-id"]}';
const realCaseButton=node('button','Зафиксировать снимок реального кейса');realCaseButton.type='submit';
realCaseForm.append(realCaseJob,realCaseManifest,realCaseButton);
const realCaseStatus=node('p');const realCaseResults=node('div');
realCasePanel.append(realCaseStatus,realCaseForm,realCaseResults);domainPanel.after(realCasePanel);
realCaseForm.onsubmit=async event=>{event.preventDefault();if(!current||pending||!realCaseJob.value)return;let manifest=null;if(realCaseManifest.value.trim()){try{manifest=JSON.parse(realCaseManifest.value);}catch(_){error('Manifest ролей исходников должен быть корректным JSON');return;}}const session=current;pending=true;realCaseButton.disabled=true;error(null);try{await api(`/api/sessions/${session}/real-case`,{method:'POST',body:{job_id:realCaseJob.value,expected_revision:realCaseRevision,manifest}});await refresh();}catch(e){error(e);}finally{pending=false;realCaseButton.disabled=false;controls();}};
function renderRealCase(report,jobs){
 realCaseRevision=report.revision||0;
 const previous=realCaseJob.value;realCaseJob.replaceChildren();const blank=node('option','Выберите завершённый CORE_RUN');blank.value='';realCaseJob.append(blank);
 for(const j of jobs.filter(j=>j.mode==='CORE_RUN'&&j.result)){const o=node('option',(j.state==='SUCCEEDED'?'✓ ':'')+j.prompt.slice(0,90));o.value=j.id;realCaseJob.append(o);}if([...realCaseJob.options].some(o=>o.value===previous))realCaseJob.value=previous;
 realCaseStatus.textContent=report.cases?.length?`Версий: ${report.revision} · ${report.status} · текущий снимок ${report.current_fresh?'актуален':'устарел'} · FINAL AUDIT NOT_RUN`:'Реальный кейс ещё не зафиксирован.';
 realCaseResults.replaceChildren();
 for(const item of (report.cases||[]).slice(-5).reverse()){const card=node('article',undefined,'real-case-result');card.append(node('strong',`Кейс #${item.revision} · ${item.point7_readiness}`),node('p','SHA256: '+item.case_sha256),node('p','Роли исходников: '+Object.keys(item.source_manifest||{}).join(', ')),node('small',(item.current?'текущий':'исторический')+' · '+(item.fresh?'актуален':'не актуален')));
  for(const [name,stage] of Object.entries(item.stages)){card.append(node('p',name+' · '+stage.status),node('small',(stage.reasons||[]).join(', ')));}
  if(item.stale_reasons?.length)card.append(node('small','Изменения после снимка: '+item.stale_reasons.join(', ')));
  card.append(node('small','acceptance=false · FINAL AUDIT NOT_RUN'));realCaseResults.append(card);}
}
for(const form of [normativeForm,calculationForm,advancedDomainForm]){form.addEventListener('input',()=>{if(!domainDraftRevisions.has(form))domainDraftRevisions.set(form,domainRevision);});const currentButton=node('button','Использовать текущую версию после сверки','domain-use-current-revision');currentButton.type='button';currentButton.onclick=()=>{domainDraftRevisions.set(form,domainRevision);error(null);};form.append(currentButton);}
let domainCandidates=[];
async function submitDomain(form,packet){if(!current||pending||uploading)return;const session=current;pending=true;controls();normButton.disabled=true;calcButton.disabled=true;advancedButton.disabled=true;error(null);try{await api(`/api/sessions/${session}/domain-packets`,{method:'POST',body:{expected_revision:domainDraftRevisions.get(form)??domainRevision,packet}});form.reset();quantityToggle.onchange();domainDraftRevisions.delete(form);await refresh();}catch(e){error(e);}finally{pending=false;normButton.disabled=false;calcButton.disabled=false;advancedButton.disabled=false;controls();}}
normativeForm.onsubmit=event=>{event.preventDefault();const packet={kind:'NORMATIVE',chain:Object.fromEntries(Object.entries(chainInputs).map(([k,v])=>[k,v.value])),norm_ids:[normSource.value],actual_ids:[actualSource.value],quantities:null};if(quantityToggle.checked){const quantities={operator:operator.value};for(const kind of ['actual','limit'])quantities[kind]={candidate_id:kind==='actual'?actualSource.value:normSource.value,value:quantityInputs[kind+'-value'].value,unit:quantityInputs[kind+'-unit'].value,fragment:quantityInputs[kind+'-fragment'].value};packet.quantities=quantities;}submitDomain(normativeForm,packet);};
calculationForm.onsubmit=event=>{event.preventDefault();const bindings=[];for(const [role,select] of Object.entries(calcSelects)){const candidate=domainCandidates.find(c=>c.id===select.value);if(candidate)bindings.push({role,file_id:candidate.file_id,candidate_ids:[candidate.id]});}if(!bindings.length){error('Выберите хотя бы один расчётный источник');return;}submitDomain(calculationForm,{kind:'CALCULATION',bindings});};
advancedDomainForm.onsubmit=event=>{event.preventDefault();let packet;try{packet=JSON.parse(advancedDomainJson.value);}catch(_){error('Расширенный пакет должен быть корректным JSON');return;}if(!packet||typeof packet!=='object'||Array.isArray(packet)){error('Расширенный пакет должен быть JSON-объектом');return;}submitDomain(advancedDomainForm,packet);};
function resetDomains(){domainDraftRevisions.clear();domainRevision=0;domainOptionsKey='';normativeForm.reset();calculationForm.reset();advancedDomainForm.reset();quantityToggle.onchange();}
function renderDomains(report,candidates){domainRevision=report.revision;domainCandidates=candidates;domainStatus.textContent='Версий: '+report.revision+' · '+report.status+' · инженерное принятие отсутствует';const key=JSON.stringify(candidates.map(c=>[c.id,c.name,c.quote,c.review_revision]));if(key!==domainOptionsKey){domainOptionsKey=key;for(const select of domainPanel.querySelectorAll('.domain-source-select')){const old=select.value;select.replaceChildren();const blank=node('option','Источник не выбран');blank.value='';select.append(blank);for(const candidate of candidates){const o=node('option',candidate.name+' · '+candidate.quote.slice(0,100));o.value=candidate.id;select.append(o);}select.value=old;}}
 domainResults.replaceChildren();for(const packet of report.packets){const card=node('article',undefined,'domain-packet-result');card.append(node('strong',packet.kind+' · версия '+packet.revision+' · '+packet.status),node('p',packet.traceability),node('p','Пункт 6: '+(packet.point6_readiness||'BLOCKED_PREREQUISITES')),node('small',packet.reasons.join(', ')));
 const checks=[['Источник нормы',packet.authority_source],['Применимость нормы',packet.authority_review],['Классы данных',packet.data_class_review],['Семантика расчёта',packet.semantic_review],['Exchange',packet.exchange_review],['Solver receipt',packet.solver_review],['Execution identity',packet.execution_review],['Результаты',packet.result_review],['Фактическая конструкция',packet.structure_review]];for(const [label,value] of checks)if(value)card.append(node('small',label+': '+value.status));if(packet.kind==='NORMATIVE')for(const [key,label] of Object.entries(chainLabels))card.append(node('p',label+': '+packet.packet.chain[key]));if(packet.arithmetic){const a=packet.arithmetic;card.append(node('p','Арифметика: '+a.actual_si+' '+a.operator+' '+a.limit_si+' · '+(a.satisfied?'условие выполнено':'условие не выполнено')),node('small','Сравнение введённых значений. Истинность факта и применимость нормы не подтверждены.'));}if(packet.intake)card.append(node('p','Роли: '+packet.packet.bindings.map(b=>b.role).join(', ')),node('small','Отсутствуют: '+packet.intake.missing_roles.join(', ')));for(const source of packet.sources)card.append(node('blockquote',source.quote),node('small',source.candidate_id+' · '+source.status+' · SHA256 '+source.source_sha256));domainResults.append(card);}}
