'use strict';
const token=document.querySelector('meta[name="app-token"]').content;
const $=id=>document.getElementById(id);
let recovery=false,busy=false;
function controls(){for(const id of ['archive-path','restore-target','activate-root','backup-create','backup-verify','backup-restore','activate-project'])$(id).disabled=!recovery||busy;}
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:{'X-Engineer-Token':token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error||'Операция не выполнена');return data;}
async function operation(action){if(!recovery||busy)return;const archive=$('archive-path').value.trim(),target=(action==='activate'?$('activate-root'):$('restore-target')).value.trim();if(action!=='activate'&&!$('archive-path').reportValidity())return;if(['restore','activate'].includes(action)&&!(action==='activate'?$('activate-root'):$('restore-target')).reportValidity())return;busy=true;controls();$('recovery-error').hidden=true;$('recovery-result').textContent='Операция выполняется. Дождитесь результата; большие архивы требуют времени.';
try{const result=await api('/api/data/'+action,{...(action!=='activate'?{archive}:{}),...(['restore','activate'].includes(action)?{target}:{})});const labels={backup:'Копия создана и проверена',verify:'Целостность архива проверена',restore:'Проект восстановлен в новый каталог',activate:'Каталог выбран для следующего запуска'};$('recovery-result').textContent=labels[action]+(result.path?' · '+result.path:'')+(result.files!==undefined?' · элементов: '+result.files:'');if(action==='restore'||action==='activate'){$('data-root').textContent=result.path;$('activate-root').value=result.path;}}
catch(e){$('recovery-error').hidden=false;$('recovery-error').textContent=e.message;$('recovery-result').textContent='Операция не завершена. Рабочие данные не заменены; проверьте путь и состояние приложения.';}finally{busy=false;controls();}}
$('backup-create').onclick=()=>operation('backup');$('backup-verify').onclick=()=>operation('verify');$('backup-restore').onclick=()=>operation('restore');$('activate-form').onsubmit=e=>{e.preventDefault();operation('activate');};
controls();api('/api/data/status').then(data=>{recovery=data.recovery_only;$('data-root').textContent=data.root;$('activate-root').value=data.root;$('recovery-mode').textContent=recovery?'Режим обслуживания · оригиналы не заменяются':'Открыт работающий кабинет. Остановите его и запустите Recover_ENGINEER_OS.cmd — сейчас операции отключены.';controls();}).catch(e=>{$('recovery-error').hidden=false;$('recovery-error').textContent=e.message;});
