/* DOM integration (jsdom), actual launcher/worker, synthetic model protocol.
   This verifies UI behavior, not browser rendering or Windows. */
const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const http=require('node:http');const {spawn}=require('node:child_process');const {JSDOM,VirtualConsole}=require('jsdom');
async function until(check){const end=Date.now()+10000;while(Date.now()<end){if(check())return;await new Promise(resolve=>setTimeout(resolve,40));}throw new Error('DOM condition timeout');}
(async()=>{
 const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'engineer-os-dom-'));
 const requests=[],errors=[];let child,dom,failAt;
 const model=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');if(req.method==='GET'){res.end(JSON.stringify(req.url==='/api/tags'?{models:[{name:'qwen3:8b',digest:'sha256:'+'a'.repeat(64)}]}:{data:[{id:'qwen3:8b'}]}));return;}let raw='';req.on('data',data=>raw+=data);req.on('end',()=>{const payload=JSON.parse(raw);if(req.url==='/api/show'){res.end(JSON.stringify({parameters:'num_ctx 8192',template:'stable'}));return;}requests.push(payload);if(requests.length===failAt){res.statusCode=503;res.end('{}');return;}const content=payload.messages[0].content.includes('Назначенная роль:')?JSON.stringify({status:'UNCERTAINTY',summary:'Черновик <script>window.coreInjected=true</script>',observations:[],limitations:['Источник не проверен']}):'СИНТЕТИЧЕСКИЙ ОТВЕТ. <script>window.injected=true</script>';res.end(JSON.stringify({choices:[{message:{content}}]}));});});
 try{
  await new Promise(resolve=>model.listen(0,'127.0.0.1',resolve));
  child=spawn(process.env.PYTHON||'python3',['scripts/run_local_app.py','--no-browser','--port','0','--data-dir',temp],{cwd:root,env:{...process.env,GOOGLE_DRIVE_CLIENT_ID:'',GOOGLE_DRIVE_CLIENT_SECRET:'',GOOGLE_DRIVE_REFRESH_TOKEN:'',ENGINEER_OS_LOCAL_MODEL_URL:`http://127.0.0.1:${model.address().port}`,ENGINEER_OS_LOCAL_MODEL:'qwen3:8b',ENGINEER_OS_LOCAL_PROVIDER:'ollama',ENGINEER_OS_LOCAL_MODEL_KEY:''}});
  const origin=await new Promise((resolve,reject)=>{let log='';const timer=setTimeout(()=>reject(Error('Launcher timeout')),10000);child.stdout.on('data',data=>{log+=data;const f=log.match(/ENGINEER OS: (http:\/\/127\.0\.0\.1:\d+)/);if(f){clearTimeout(timer);resolve(f[1]);}});child.on('exit',code=>{clearTimeout(timer);reject(Error(`Launcher exited ${code}`));});});
  const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
  async function open(){return JSDOM.fromURL(origin,{resources:'usable',runScripts:'dangerously',virtualConsole:vc,beforeParse(win){win.fetch=(input,options)=>fetch(new URL(input,origin),options);}});}
  dom=await open();let win=dom.window,doc=win.document;await until(()=>doc.querySelector('nav .session')&&!doc.querySelector('#prompt').disabled);
  const source=Buffer.from('ТЗ: высота 4 м');const upload=doc.querySelector('#upload');Object.defineProperty(upload,'files',{value:[{name:'ТЗ.md',size:source.length,arrayBuffer:async()=>new win.Uint8Array(source).buffer}]});
  upload.dispatchEvent(new win.Event('change'));try{await until(()=>doc.querySelector('.file')&&!doc.querySelector('#send').disabled);}catch(e){throw new Error(e.message+': '+doc.querySelector('#error').textContent+' / '+errors.join(';'));}
  assert.ok(doc.querySelector('.file .coverage'),'File extraction coverage must be visible');
  assert.ok(doc.querySelector('.file .coverage').textContent.includes('Полнота документа не проверена'));
  doc.querySelector('#prompt').value='Проверь высоту по ТЗ';doc.querySelector('#composer').dispatchEvent(new win.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.message.assistant')&&!doc.querySelector('#send').disabled);
  assert.equal(requests.length,1);assert.ok(JSON.stringify(requests[0]).includes('высота 4 м'));assert.equal(win.injected,undefined);
  assert.equal(doc.querySelector('nav .session').disabled,false,'Conversation navigation must re-enable after sending');
  dom.window.close();dom=await open();win=dom.window;doc=win.document;await until(()=>doc.querySelector('.message.assistant'));assert.equal(doc.querySelectorAll('.file').length,1);
  doc.querySelector('#new-chat').click();await until(()=>doc.querySelectorAll('nav .session').length===2&&doc.querySelectorAll('.message').length===0);
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();await until(()=>doc.querySelector('.message.assistant'));
  assert.ok(doc.querySelector('#task-mode'),'Explicit engineering preparation mode must be available');
  doc.querySelector('#task-mode').value='CORE_PLAN';doc.querySelector('.file input').click();
  doc.querySelector('#prompt').value='ТЗ: проверить отчёт и нормы';
  doc.querySelector('#composer').dispatchEvent(new win.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.core-plan')&&!doc.querySelector('#send').disabled);
  assert.equal(requests.length,1,'CORE preparation must not call model');
  assert.ok(doc.querySelector('.core-plan').textContent.includes('FINAL AUDIT'));
  assert.ok(doc.querySelector('.core-plan').textContent.includes('ТЗ.md'));
  dom.window.close();dom=await open();doc=dom.window.document;
  await until(()=>doc.querySelectorAll('nav .session').length===2);
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.core-plan'));
  assert.ok(doc.querySelector('#evidence-form'),'Source candidate form must exist');
  doc.querySelector('#evidence-file').value=doc.querySelector('#evidence-file option').value;
  doc.querySelector('#evidence-quote').value='ТЗ: высота 4 м';
  doc.querySelector('#evidence-statement').value='<script>window.forged=true</script>';
  doc.querySelector('#evidence-form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.evidence-card'));
  assert.ok(doc.querySelector('.evidence-card').textContent.includes('UNVERIFIED'));
  assert.ok(doc.querySelector('.provenance-status').textContent.includes('неприменимы'),'TXT must not invent PDF geometry');
  assert.equal(dom.window.forged,undefined);
  dom.window.close();dom=await open();doc=dom.window.document;
  await until(()=>doc.querySelectorAll('nav .session').length===2);
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.evidence-card'));
  doc.querySelector('#evidence-quote').value='Unsaved previous source';
  doc.querySelector('#evidence-statement').value='Unsaved previous assertion';
  doc.querySelector('#evidence-page').value='12';
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Новый диалог').click();
  await until(()=>doc.querySelector('#title').textContent==='Новый диалог');
  assert.equal(doc.querySelector('#evidence-quote').value,'','Draft source quote must not cross conversations');
  assert.equal(doc.querySelector('#evidence-statement').value,'');
  assert.equal(doc.querySelector('#evidence-page').value,'');
  assert.ok(doc.querySelector('#source-viewer'),'Persistent source viewer must exist');
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.evidence-card'));
  const pdf=require('node:child_process').execFileSync(process.env.PYTHON||'python3',['-c',"import fitz,sys; d=fitz.open();d.new_page().insert_text((40,40),'height 4m');sys.stdout.buffer.write(d.tobytes())"]);
  const token=doc.querySelector('meta[name="app-token"]').content;
  const sessions=await (await fetch(origin+'/api/sessions',{headers:{'X-Engineer-Token':token}})).json();
  const id=sessions.find(s=>s.title==='Проверь высоту по ТЗ').id;
  const file=await (await fetch(origin+`/api/sessions/${id}/files?name=preview.pdf`,{method:'POST',headers:{'X-Engineer-Token':token,'Content-Type':'application/octet-stream'},body:pdf})).json();
  await fetch(origin+`/api/sessions/${id}/evidence`,{method:'POST',headers:{'X-Engineer-Token':token,'Content-Type':'application/json'},body:JSON.stringify({file_id:file.id,page:1,quote:'height 4m',statement:'Unverified preview'})});
  await until(()=>doc.querySelector('.preview-button'));
  doc.querySelector('.preview-button').click();
  await until(()=>doc.querySelector('#source-image').src.startsWith('data:image/png'));
  assert.ok(doc.querySelector('#source-caption').textContent.includes('preview.pdf'));
  const pdfCard=[...doc.querySelectorAll('.file')].find(c=>c.textContent.includes('preview.pdf'));
  assert.ok(pdfCard.querySelector('.coverage').textContent.includes('1/1'),'Actual PDF coverage must be visible');
  assert.ok(doc.querySelector('#source-caption').textContent.includes('не подтверждает'));
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Новый диалог').click();
  await until(()=>doc.querySelector('#title').textContent==='Новый диалог');
  assert.equal(doc.querySelector('#source-viewer').hidden,true,'Preview must not cross conversations');
  assert.ok(doc.querySelector('#review-form'),'Persistent review form missing');
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.review-button'));
  doc.querySelector('.review-button').click();
  doc.querySelector('#review-decision').value='SOURCE_CONFIRMED';
  doc.querySelector('#review-note').value='Source checked <script>window.reviewInjected=true</script>';
  doc.querySelector('#review-actor').value='Local reviewer';
  await new Promise(resolve=>setTimeout(resolve,1700));
  assert.ok(doc.querySelector('#review-note').value.includes('Source checked'),'Polling must preserve review draft');
  doc.querySelector('#review-form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.review-history'));
  assert.equal(dom.window.reviewInjected,undefined);
  assert.ok(doc.querySelector('.review-history').textContent.includes('Source checked'));
  doc.querySelector('.review-button').click();doc.querySelector('#review-note').value='Unsaved review';
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Новый диалог').click();
  await until(()=>doc.querySelector('#title').textContent==='Новый диалог');
  assert.equal(doc.querySelector('#review-panel').hidden,true);
  assert.equal(doc.querySelector('#review-note').value,'');
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.file input'));
  assert.ok(doc.querySelector('#task-mode option[value="CORE_RUN"]'),'Profile execution mode missing');
  doc.querySelector('#task-mode').value='CORE_RUN';doc.querySelector('#task-mode').dispatchEvent(new dom.window.Event('change'));
  assert.ok(doc.querySelector('#core-checks'),'Selectable specialist checks missing');
  doc.querySelector('.file input').click();doc.querySelector('#prompt').value='Предварительно проверить отчёт и нормы';
  doc.querySelector('#composer').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.core-run')&&!doc.querySelector('#send').disabled);
  assert.equal(requests.length,4,'Three specialist calls should follow one chat call');
  assert.ok(doc.querySelector('.core-run').textContent.includes('UNCERTAINTY'));
  assert.ok(doc.querySelector('.core-run').textContent.includes('Черновик'));
  assert.equal(dom.window.coreInjected,undefined);
  dom.window.close();dom=await open();doc=dom.window.document;
  await until(()=>doc.querySelectorAll('nav .session').length===2);
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.core-run'));
  assert.ok(doc.querySelector('.core-run').textContent.includes('NOT_RUN'));
  const fullPdfCard=[...doc.querySelectorAll('.file')].find(c=>c.textContent.includes('preview.pdf'));
  assert.ok(fullPdfCard.querySelector('.advanced-document-actions'),'Manual extraction must be under advanced actions');
  fullPdfCard.querySelector('input').click();
  doc.querySelector('#task-mode').value='CHAT';doc.querySelector('#prompt').value='Проверь прикреплённый PDF';
  doc.querySelector('#composer').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.automatic-analysis')&&!doc.querySelector('#send').disabled);
  assert.ok(doc.querySelector('.automatic-analysis').textContent.includes('1/1'));
  assert.ok(JSON.stringify(requests.at(-1)).includes('height 4m'),'PDF is automatically supplied to analysis');
  assert.equal(requests.length,5,'One-page automatic document analysis needs one model request');
  doc.querySelector('.analysis-drafts').click();await until(()=>doc.querySelector('.analysis-receipt'));
  const largePdf=require('node:child_process').execFileSync(process.env.PYTHON||'python3',['-c',"import fitz,sys; d=fitz.open();[d.new_page().insert_textbox((30,30,570,800),'RESUME_'+str(i)+' source '*500,fontsize=8) for i in range(4)];sys.stdout.buffer.write(d.tobytes())"]);
  const largeFile=await (await fetch(origin+`/api/sessions/${id}/files?name=resume.pdf`,{method:'POST',headers:{'X-Engineer-Token':token,'Content-Type':'application/octet-stream'},body:largePdf})).json();
  const beforeResume=requests.length;failAt=beforeResume+2;
  const resumeJob=await (await fetch(origin+`/api/sessions/${id}/jobs`,{method:'POST',headers:{'X-Engineer-Token':token,'Content-Type':'application/json'},body:JSON.stringify({prompt:'Проверка продолжения',file_ids:[largeFile.id]})})).json();
  await until(()=>doc.querySelector('.analysis-resume')&&!doc.querySelector('.analysis-resume').disabled);
  const firstPayload=JSON.stringify(requests[beforeResume]);
  dom.window.close();dom=await open();doc=dom.window.document;
  await until(()=>doc.querySelectorAll('nav .session').length===2);
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.analysis-resume')&&!doc.querySelector('.analysis-resume').disabled);
  doc.querySelector('.analysis-resume').click();
  await until(()=>!doc.querySelector('.analysis-resume')&&!doc.querySelector('#send').disabled);
  const resumed=await (await fetch(origin+`/api/sessions/${id}`,{headers:{'X-Engineer-Token':token}})).json();
  const finished=resumed.jobs.find(j=>j.id===resumeJob.id);
  assert.equal(finished.state,'SUCCEEDED');assert.ok(finished.result.document_analysis.calls_reused>0);
  assert.equal(requests.filter(p=>JSON.stringify(p)===firstPayload).length,1,'Completed source part must not repeat');
  assert.equal(resumed.messages.filter(m=>m.role==='user'&&m.content==='Проверка продолжения').length,1);
  assert.ok(doc.querySelector('.automatic-analysis').textContent.includes('Повторно использовано'));
  assert.equal(resumed.jobs.filter(j=>j.id===resumeJob.id).length,1);
  assert.ok(doc.querySelector('#drive-form'),'Drive import form missing');
  await until(()=>doc.querySelector('#drive-status').textContent.includes('не настроен'));
  assert.equal(doc.querySelector('#drive-import').disabled,true,'Missing OAuth must not be shown as connected');
  assert.equal(doc.querySelectorAll('.file').length,3,'Unavailable Drive must not manufacture an imported file');
  assert.equal(errors.length,0,errors.join('\n'));console.log(JSON.stringify({result:'PASS',dom_emulation:true,browser_visual_check:false,synthetic_model:true,real_ollama:false,checks:['launcher','background-worker','upload-action','source-context','chat','inert-markup','history-reload','session-switch','core-plan-no-model','core-plan-reload','evidence-register','inert-evidence','evidence-reload','evidence-draft-isolation','source-preview','preview-isolation','source-review','review-draft-poll','review-isolation','core-run-three-roles','core-run-inert-output','core-run-history-reload','drive-unconfigured','no-fabricated-import','file-extraction-coverage','pdf-page-coverage','automatic-pdf-analysis','advanced-document-actions','analysis-receipts'],requests:requests.length}));
 }finally{
  if(dom)dom.window.close();if(child){child.kill('SIGINT');await new Promise(resolve=>{if(child.exitCode!==null)return resolve();const t=setTimeout(()=>{child.kill('SIGKILL');resolve();},2500);child.once('exit',()=>{clearTimeout(t);resolve();});});}
  await new Promise(resolve=>model.close(resolve));fs.rmSync(temp,{recursive:true,force:true});
 }
})().catch(e=>{console.error(e);process.exitCode=1;});
