/* DOM integration (jsdom), actual launcher/worker, synthetic model protocol.
   This verifies UI behavior, not browser rendering or Windows. */
const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const http=require('node:http');const {spawn}=require('node:child_process');const {JSDOM,VirtualConsole}=require('jsdom');
async function until(check){const end=Date.now()+10000;while(Date.now()<end){if(check())return;await new Promise(resolve=>setTimeout(resolve,40));}throw new Error('DOM condition timeout');}
(async()=>{
 const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'engineer-os-dom-'));
 const requests=[],errors=[];let child,dom,failAt;
 const model=http.createServer((req,res)=>{res.setHeader('Content-Type','application/json');if(req.method==='GET'){res.end(JSON.stringify(req.url==='/api/tags'?{models:[{name:'qwen3:8b',digest:'sha256:'+'a'.repeat(64)}]}:{data:[{id:'qwen3:8b'}]}));return;}let raw='';req.on('data',data=>raw+=data);req.on('end',()=>{const payload=JSON.parse(raw);if(req.url==='/api/show'){res.end(JSON.stringify({parameters:'num_ctx 8192',template:'stable'}));return;}requests.push(payload);if(requests.length===failAt){res.statusCode=503;res.end('{}');return;}const content=payload.messages[0].content.includes('Назначенная роль:')?JSON.stringify({status:'UNCERTAINTY',summary:'Черновик <script>window.coreInjected=true</script>',observations:[{text:"Пример непроверенного наблюдения",source_ids:[]}],limitations:['Источник не проверен']}):'СИНТЕТИЧЕСКИЙ ОТВЕТ. <script>window.injected=true</script>';res.end(JSON.stringify({choices:[{message:{content}}]}));});});
 try{
  await new Promise(resolve=>model.listen(0,'127.0.0.1',resolve));
  child=spawn(process.env.PYTHON||'python3',['scripts/run_local_app.py','--no-browser','--port','0','--data-dir',temp],{cwd:root,env:{...process.env,GOOGLE_DRIVE_CLIENT_ID:'',GOOGLE_DRIVE_CLIENT_SECRET:'',GOOGLE_DRIVE_REFRESH_TOKEN:'',ENGINEER_OS_LOCAL_MODEL_URL:`http://127.0.0.1:${model.address().port}`,ENGINEER_OS_LOCAL_MODEL:'qwen3:8b',ENGINEER_OS_LOCAL_PROVIDER:'ollama',ENGINEER_OS_LOCAL_MODEL_KEY:''}});
  const origin=await new Promise((resolve,reject)=>{let log='';const timer=setTimeout(()=>reject(Error('Launcher timeout')),10000);child.stdout.on('data',data=>{log+=data;const f=log.match(/ENGINEER OS: (http:\/\/127\.0\.0\.1:\d+)/);if(f){clearTimeout(timer);resolve(f[1]);}});child.on('exit',code=>{clearTimeout(timer);reject(Error(`Launcher exited ${code}`));});});
  const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
  async function open(){return JSDOM.fromURL(origin,{resources:'usable',runScripts:'dangerously',virtualConsole:vc,beforeParse(win){win.fetch=(input,options)=>fetch(new URL(input,origin),options);}});}
  dom=await open();let win=dom.window,doc=win.document;await until(()=>doc.querySelector('nav .session')&&!doc.querySelector('#prompt').disabled);
  assert.equal(doc.querySelectorAll('#project-route button').length,6,'Six project stages must be reachable');
  assert.ok(doc.querySelector('#project-next').textContent.includes('документ'),'Empty project needs an actionable next step');
  doc.querySelector('[data-stage="documents"]').click();
  assert.equal(doc.querySelector('.drive-panel').open,true,'Document navigation must open import');
  const source=Buffer.from('ТЗ: высота 4 м');const upload=doc.querySelector('#upload');Object.defineProperty(upload,'files',{value:[{name:'ТЗ.md',size:source.length,arrayBuffer:async()=>new win.Uint8Array(source).buffer}]});
  upload.dispatchEvent(new win.Event('change'));try{await until(()=>doc.querySelector('.file')&&!doc.querySelector('#send').disabled);}catch(e){throw new Error(e.message+': '+doc.querySelector('#error').textContent+' / '+errors.join(';'));}
  assert.ok(doc.querySelector('.file .coverage'),'File extraction coverage must be visible');
  assert.ok(doc.querySelector('.file .coverage').textContent.includes('Полнота документа не проверена'));
  doc.querySelector('#prompt').value='Проверь высоту по ТЗ';doc.querySelector('#composer').dispatchEvent(new win.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.message.assistant')&&!doc.querySelector('#send').disabled);
  assert.equal(requests.length,1);assert.ok(JSON.stringify(requests[0]).includes('высота 4 м'));assert.equal(win.injected,undefined);
  assert.equal(doc.querySelector('nav .session').disabled,false,'Conversation navigation must re-enable after sending');
  dom.window.close();dom=await open();win=dom.window;doc=win.document;await until(()=>doc.querySelector('.message.assistant'));assert.equal(doc.querySelectorAll('.file').length,1);
  doc.querySelector('#new-chat').click();await until(()=>doc.querySelectorAll('nav .session').length===2&&doc.querySelectorAll('.message').length===0);
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();await until(()=>doc.querySelector('.message.assistant'));
  assert.ok(doc.querySelector('#task-mode'),'Explicit engineering preparation mode must be available');
  assert.ok(doc.querySelector('#tz-sources'),'ToR source selector missing');
  doc.querySelector('#task-mode').value='CORE_PLAN';doc.querySelector('.file input').click();
  doc.querySelector('#prompt').value='ТЗ: проверить отчёт и нормы';
  doc.querySelector('#composer').dispatchEvent(new win.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.core-plan')&&!doc.querySelector('#send').disabled);
  assert.equal(requests.length,1,'CORE preparation must not call model');
  assert.ok(doc.querySelector('.core-plan').textContent.includes('FINAL AUDIT'));
  assert.ok(doc.querySelector('.core-plan').textContent.includes('ТЗ.md'));
  dom.window.close();dom=await open();doc=dom.window.document;
  await until(()=>doc.querySelectorAll('nav .session').length===2);
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.core-plan'));
  assert.ok(doc.querySelector('#evidence-form'),'Source candidate form must exist');
  doc.querySelector('#evidence-file').value=doc.querySelector('#evidence-file option').value;
  doc.querySelector('#evidence-quote').value='ТЗ: высота 4 м';
  doc.querySelector('#evidence-statement').value='<script>window.forged=true</script>';
  doc.querySelector('#evidence-form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.evidence-card'));
  assert.ok(doc.querySelector('.evidence-card').textContent.includes('UNVERIFIED'));
  assert.ok(doc.querySelector('.provenance-status').textContent.includes('неприменимы'),'TXT must not invent PDF geometry');
  assert.equal(dom.window.forged,undefined);
  dom.window.close();dom=await open();doc=dom.window.document;
  await until(()=>doc.querySelectorAll('nav .session').length===2);
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.evidence-card'));
  doc.querySelector('#evidence-quote').value='Unsaved previous source';
  doc.querySelector('#evidence-statement').value='Unsaved previous assertion';
  doc.querySelector('#evidence-page').value='12';
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Новый диалог').click();
  await until(()=>doc.querySelector('#title').textContent==='Новый диалог');
  assert.equal(doc.querySelector('#evidence-quote').value,'','Draft source quote must not cross conversations');
  assert.equal(doc.querySelector('#evidence-statement').value,'');
  assert.equal(doc.querySelector('#evidence-page').value,'');
  assert.ok(doc.querySelector('#source-viewer'),'Persistent source viewer must exist');
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.evidence-card'));
  const pdf=require('node:child_process').execFileSync(process.env.PYTHON||'python3',['-c',"import fitz,sys; d=fitz.open();d.new_page().insert_text((40,40),'height 4m');sys.stdout.buffer.write(d.tobytes())"]);
  const token=doc.querySelector('meta[name="app-token"]').content;
  const sessions=await (await fetch(origin+'/api/sessions',{headers:{'X-Engineer-Token':token}})).json();
  const id=sessions.find(s=>s.title==='Проверь высоту по ТЗ').id;
  const file=await (await fetch(origin+`/api/sessions/${id}/files?name=preview.pdf`,{method:'POST',headers:{'X-Engineer-Token':token,'Content-Type':'application/octet-stream'},body:pdf})).json();
  await fetch(origin+`/api/sessions/${id}/evidence`,{method:'POST',headers:{'X-Engineer-Token':token,'Content-Type':'application/json'},body:JSON.stringify({file_id:file.id,page:1,quote:'height 4m',statement:'Unverified preview'})});
  await until(()=>doc.querySelector('.preview-button'));
  doc.querySelector('.preview-button').click();
  await until(()=>doc.querySelector('#source-image').src.startsWith('data:image/png'));
  assert.ok(doc.querySelector('#source-caption').textContent.includes('preview.pdf'));
  const pdfCard=[...doc.querySelectorAll('.file')].find(c=>c.textContent.includes('preview.pdf'));
  assert.ok(pdfCard.querySelector('.coverage').textContent.includes('1/1'),'Actual PDF coverage must be visible');
  assert.ok(doc.querySelector('#source-caption').textContent.includes('не подтверждает'));
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Новый диалог').click();
  await until(()=>doc.querySelector('#title').textContent==='Новый диалог');
  assert.equal(doc.querySelector('#source-viewer').hidden,true,'Preview must not cross conversations');
  assert.ok(doc.querySelector('#review-form'),'Persistent review form missing');
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.review-button'));
  doc.querySelector('.review-button').click();
  doc.querySelector('#review-decision').value='SOURCE_CONFIRMED';
  doc.querySelector('#review-note').value='Source checked <script>window.reviewInjected=true</script>';
  doc.querySelector('#review-actor').value='Local reviewer';
  await new Promise(resolve=>setTimeout(resolve,1700));
  assert.ok(doc.querySelector('#review-note').value.includes('Source checked'),'Polling must preserve review draft');
  doc.querySelector('#review-form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.review-history'));
  assert.equal(dom.window.reviewInjected,undefined);
  assert.ok(doc.querySelector('.review-history').textContent.includes('Source checked'));
  assert.ok(doc.querySelector('#calculation-packet-form'),'Calculation source roles form missing');
  assert.ok(doc.querySelector('#advanced-domain-packet-form'),'Advanced point-6 packet import form missing');
  const initialDomainRevision=(await (await fetch(origin+`/api/sessions/${id}/domain-packets`,{headers:{'X-Engineer-Token':token}})).json()).revision;
  const domainDraft=doc.querySelector('#normative-packet-form [name="document"]');domainDraft.value='Concurrent draft';domainDraft.dispatchEvent(new dom.window.Event('input',{bubbles:true}));
  const unitRole=doc.querySelector('[data-domain-role="UNITS"]');
  unitRole.value=doc.querySelector('.evidence-card').dataset.id||doc.querySelector('#evidence-file').value;
  unitRole.value=[...unitRole.options].find(o=>o.value)?.value||'';
  assert.ok(unitRole.value,'Confirmed source candidate must be selectable for a calculation role');
  doc.querySelector('#calculation-packet-form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.domain-packet-result'));
  assert.ok(doc.querySelector('.domain-packet-result').textContent.includes('SOLVER_NOT_RUN'));
  assert.ok(doc.querySelector('.domain-packet-result').textContent.includes('UNITS'));
  assert.ok(doc.querySelector('.domain-packet-result').textContent.includes('Пункт 6: BLOCKED_PREREQUISITES'));
  async function reviewedDomainSource(name,text){
    const headers={'X-Engineer-Token':token};
    const f=await (await fetch(origin+`/api/sessions/${id}/files?name=${name}`,{method:'POST',headers:{...headers,'Content-Type':'application/octet-stream'},body:Buffer.from(text)})).json();
    const c=await (await fetch(origin+`/api/sessions/${id}/evidence`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({file_id:f.id,quote:text,statement:'Synthetic source for domain UI test'})})).json();
    const response=await fetch(origin+`/api/sessions/${id}/evidence/${c.id}/reviews`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({expected_revision:0,decision:'SOURCE_CONFIRMED',note:'Synthetic fixture source checked',actor:'Test'})});
    assert.equal(response.status,201);return c;
  }
  const normCandidate=await reviewedDomainSource('domain-norm.txt','TEST 2026 clause1 Limit 2.5 m');
  const actualCandidate=await reviewedDomainSource('domain-actual.txt','Height 2500 mm');
  await until(()=>[...doc.querySelector('[name="norm-source"]').options].some(o=>o.value===normCandidate.id));
  const nf=doc.querySelector('#normative-packet-form');
  assert.ok(nf.querySelector('[name="reviewer"]'),'Dated substantive normative review must be available without JSON');
  const chain={document:'TEST',edition:'2026',scope:'Synthetic scope declaration',clause:'clause1',requirement:'Limit 2.5 m',actual_condition:'Height 2500 mm',comparison:'Compare synthetic quantities',conclusion:'Arithmetic matches, norm unverified'};
  for(const [name,value] of Object.entries(chain))nf.querySelector(`[name="${name}"]`).value=value;
  nf.querySelector('[name="norm-source"]').value=normCandidate.id;nf.querySelector('[name="actual-source"]').value=actualCandidate.id;
  nf.querySelector('input[type="checkbox"]').click();
  for(const [name,value] of Object.entries({'actual-value':'2500','actual-unit':'mm','actual-fragment':'2500 mm','limit-value':'2.5','limit-unit':'m','limit-fragment':'2.5 m'}))nf.querySelector(`[name="${name}"]`).value=value;
  const domainWrites=[];const delegatedFetch=dom.window.fetch;
  dom.window.fetch=(path,options)=>{if(String(path).endsWith('/domain-packets')&&options?.method==='POST')domainWrites.push(JSON.parse(options.body));return delegatedFetch(path,options);};
  nf.dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>domainWrites.length===1);
  assert.equal(domainWrites[0].expected_revision,initialDomainRevision,'Saving calculation must retain normative draft revision');
  await until(()=>!doc.querySelector('#error').hidden&&!doc.querySelector('#send').disabled);
  nf.querySelector('.domain-use-current-revision').click();
  nf.dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>[...doc.querySelectorAll('.domain-packet-result')].some(c=>c.textContent.includes('Арифметика: 2.500 <= 2.5')));
  assert.ok(doc.querySelector('.domain-panel').textContent.includes('NORMATIVE_APPLICABILITY_NOT_VERIFIED'));
  for(const [name,value] of Object.entries(chain))nf.querySelector(`[name="${name}"]`).value=value;
  nf.querySelector('[name="norm-source"]').value=normCandidate.id;nf.querySelector('[name="actual-source"]').value=actualCandidate.id;
  nf.querySelector('#normative-review-toggle').click();
  for(const [name,value] of Object.entries({reviewer:'DOM reviewer',reviewed_at:'2026-10-08',assessment_date:'2026-07-28',edition_basis:'Registry inspected',applicability_basis:'Synthetic concrete scope',rationale:'Calibration requires additional data',limitations:'Not field verified'}))nf.querySelector(`[name="${name}"]`).value=value;
  nf.querySelector('[name="applicability"]').value='APPLIES';nf.querySelector('[name="input_status"]').value='DOCUMENTED';nf.querySelector('[name="outcome"]').value='BLOCK';
  nf.dispatchEvent(new dom.window.Event('input',{bubbles:true}));nf.dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>[...doc.querySelectorAll('.domain-packet-result')].some(c=>c.textContent.includes('DOM reviewer')));
  assert.ok(doc.querySelector('.domain-panel').textContent.includes('Calibration requires additional data'));
  nf.querySelector('[name="document"]').value='Unsaved domain from previous session';
  doc.querySelector('.review-button').click();doc.querySelector('#review-note').value='Unsaved review';
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Новый диалог').click();
  await until(()=>doc.querySelector('#title').textContent==='Новый диалог');
  assert.equal(doc.querySelector('#normative-packet-form [name="document"]').value,'','Domain drafts must not cross conversations');
  assert.equal(doc.querySelector('#review-panel').hidden,true);
  assert.equal(doc.querySelector('#review-note').value,'');
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.file input'));
  assert.ok(doc.querySelector('#task-mode option[value="CORE_RUN"]'),'Profile execution mode missing');
  doc.querySelector('#task-mode').value='CORE_RUN';doc.querySelector('#task-mode').dispatchEvent(new dom.window.Event('change'));
  assert.ok(doc.querySelector('#core-checks'),'Selectable specialist checks missing');
  doc.querySelector('.file input').click();doc.querySelector('#prompt').value='Предварительно проверить отчёт и нормы';
  doc.querySelector('#composer').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.core-run')&&!doc.querySelector('#send').disabled);
  assert.equal(requests.length,4,'Three specialist calls should follow one chat call');
  assert.ok(doc.querySelector('.core-run').textContent.includes('UNCERTAINTY'));
  assert.ok(doc.querySelector('.core-run').textContent.includes('Черновик'));
  assert.ok(doc.querySelector('.specialist-checks')?.textContent.includes('Редакция нормы не подтверждена'),'Domain prerequisites must be visible');
  assert.ok(doc.querySelector('.core-run summary').textContent.includes('BLOCK'),'Domain BLOCK must survive a completed draft');
  assert.ok(doc.querySelector('.engineering-review').textContent.includes('BLOCK'));
  assert.ok(doc.querySelector('.engineering-review').textContent.includes('Воспроизводимый снимок'));
  assert.ok(JSON.stringify(requests.at(-1)).includes('NORMATIVE_EDITION_NOT_VERIFIED'),'Audit must receive deterministic domain gaps');
  assert.equal(dom.window.coreInjected,undefined);
  assert.ok(doc.querySelector('.finding-gate')?.textContent.includes('NO_CANDIDATE_REFERENCE'),'Unlinked findings must show their deterministic source BLOCK');
  dom.window.close();dom=await open();doc=dom.window.document;
  await until(()=>doc.querySelectorAll('nav .session').length===2);
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.core-run'));
  assert.ok(doc.querySelector('.core-run').textContent.includes('NOT_RUN'));
  const fullPdfCard=[...doc.querySelectorAll('.file')].find(c=>c.textContent.includes('preview.pdf'));
  assert.ok(fullPdfCard.querySelector('.advanced-document-actions'),'Manual extraction must be under advanced actions');
  const fullPdfCheck=fullPdfCard.querySelector('input');for(const check of doc.querySelectorAll('.file input:checked'))if(check!==fullPdfCheck)check.click();if(!fullPdfCheck.checked)fullPdfCheck.click();
  doc.querySelector('#task-mode').value='CHAT';doc.querySelector('#prompt').value='Проверь прикреплённый PDF';
  doc.querySelector('#composer').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.automatic-analysis')&&!doc.querySelector('#send').disabled);
  assert.ok(doc.querySelector('.automatic-analysis').textContent.includes('1/1'));
  assert.ok(JSON.stringify(requests.at(-1)).includes('height 4m'),'PDF is automatically supplied to analysis');
  assert.equal(requests.length,5,'One-page automatic document analysis needs one model request');
  doc.querySelector('.analysis-drafts').click();await until(()=>doc.querySelector('.analysis-receipt'));
  const largePdf=require('node:child_process').execFileSync(process.env.PYTHON||'python3',['-c',"import fitz,sys; d=fitz.open();[d.new_page().insert_textbox((30,30,570,800),'RESUME_'+str(i)+' source '*500,fontsize=8) for i in range(4)];sys.stdout.buffer.write(d.tobytes())"]);
  const largeFile=await (await fetch(origin+`/api/sessions/${id}/files?name=resume.pdf`,{method:'POST',headers:{'X-Engineer-Token':token,'Content-Type':'application/octet-stream'},body:largePdf})).json();
  const beforeResume=requests.length;failAt=beforeResume+2;
  const resumeJob=await (await fetch(origin+`/api/sessions/${id}/jobs`,{method:'POST',headers:{'X-Engineer-Token':token,'Content-Type':'application/json'},body:JSON.stringify({prompt:'Проверка продолжения',file_ids:[largeFile.id]})})).json();
  await until(()=>doc.querySelector('.analysis-resume')&&!doc.querySelector('.analysis-resume').disabled);
  const firstPayload=JSON.stringify(requests[beforeResume]);
  dom.window.close();dom=await open();doc=dom.window.document;
  await until(()=>doc.querySelectorAll('nav .session').length===2);
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.analysis-resume')&&!doc.querySelector('.analysis-resume').disabled);
  doc.querySelector('.analysis-resume').click();
  await until(()=>!doc.querySelector('.analysis-resume')&&!doc.querySelector('#send').disabled);
  const resumed=await (await fetch(origin+`/api/sessions/${id}`,{headers:{'X-Engineer-Token':token}})).json();
  const finished=resumed.jobs.find(j=>j.id===resumeJob.id);
  assert.equal(finished.state,'SUCCEEDED');assert.ok(finished.result.document_analysis.calls_reused>0);
  assert.equal(requests.filter(p=>JSON.stringify(p)===firstPayload).length,1,'Completed source part must not repeat');
  assert.equal(resumed.messages.filter(m=>m.role==='user'&&m.content==='Проверка продолжения').length,1);
  assert.ok(doc.querySelector('.automatic-analysis').textContent.includes('Повторно использовано'));
  assert.equal(resumed.jobs.filter(j=>j.id===resumeJob.id).length,1);
  assert.ok(doc.querySelector('#upload').accept.includes('.docx'),'Office formats must be selectable');
  const officePdf=require('node:child_process').execFileSync(process.env.PYTHON||'python3',['-c',"import sys;sys.path.insert(0,'tests');from test_office_documents import xlsx;sys.stdout.buffer.write(xlsx())"],{cwd:root});
  const officeFile=await (await fetch(origin+`/api/sessions/${id}/files?name=loads.xlsx`,{method:'POST',headers:{'X-Engineer-Token':token,'Content-Type':'application/octet-stream'},body:officePdf})).json();
  const officeJob=await (await fetch(origin+`/api/sessions/${id}/jobs`,{method:'POST',headers:{'X-Engineer-Token':token,'Content-Type':'application/json'},body:JSON.stringify({prompt:'Проверить таблицу Office',file_ids:[officeFile.id]})})).json();
  await until(()=>[...doc.querySelectorAll('.automatic-analysis')].some(c=>c.textContent.includes('loads.xlsx')&&c.textContent.includes('логических элементов'))&&!doc.querySelector('#send').disabled);
  const officeCard=[...doc.querySelectorAll('.job')].find(c=>c.textContent.includes('Проверить таблицу Office'));
  assert.ok(!officeCard.textContent.includes('4/4 страниц'),'Cell counts must not be called physical pages');
  officeCard.querySelector('.analysis-drafts').click();await until(()=>officeCard.querySelector('.analysis-receipt')||[...doc.querySelectorAll('.analysis-receipt')].some(c=>c.textContent.includes('Нагрузки!C1')));
  assert.ok([...doc.querySelectorAll('.analysis-receipt')].some(c=>c.textContent.includes('Нагрузки!C1')),'Sheet/cell locator must be visible');
  assert.ok(doc.querySelector('#tz-form'),'ТЗ checklist form must be available');
  doc.querySelector('#tz-text').value='Проверить снеговую нагрузку\nПроверить опоры';
  doc.querySelector('#tz-form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
  await until(()=>doc.querySelectorAll('.requirement-card').length===2&&!doc.querySelector('#tz-save').disabled);
  const officeReceipt=[...doc.querySelectorAll('.analysis-receipt')].find(c=>c.textContent.includes('Нагрузки!C1'));
  officeReceipt.querySelector('.candidate-from-source').click();
  await until(()=>doc.querySelector('#evidence-quote').value.includes('Снег'));
  doc.querySelector('#evidence-statement').value='Снег по таблице';doc.querySelector('#evidence-class').value='P';
  doc.querySelector('#evidence-form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
  await until(()=>[...doc.querySelectorAll('.evidence-card')].some(c=>c.textContent.includes('Снег по таблице'))&&!doc.querySelector('#evidence-save').disabled);
  let officeCandidate=[...doc.querySelectorAll('.evidence-card')].find(c=>c.textContent.includes('Снег по таблице'));
  assert.ok(officeCandidate.textContent.includes('Нагрузки!A1'));
  officeCandidate.querySelector('.review-button').click();doc.querySelector('#review-decision').value='SOURCE_CONFIRMED';doc.querySelector('#review-note').value='Адрес и значение сверены';
  doc.querySelector('#review-form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
  await until(()=>[...doc.querySelectorAll('.evidence-card')].some(c=>c.textContent.includes('Снег по таблице')&&c.querySelector('.review-history'))&&doc.querySelector('#review-panel').hidden);
  let req=doc.querySelector('.requirement-card');req.querySelector('.requirement-conclusion').value='Снег указан в ячейке';
  req.querySelector('.requirement-relation').value='SUPPORTS';req.querySelector('.requirement-actor').value='DOM reviewer';
  [...req.querySelectorAll('input[type=checkbox]')].find(c=>c.parentElement.textContent.includes('Снег по таблице')).checked=true;
  req.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
  await until(()=>doc.querySelector('.requirement-card').textContent.includes('SOURCE_LINKED'));
  assert.ok(doc.querySelector('.requirement-card').textContent.includes('UNCERTAINTY'),'Source match must not become engineering PASS');
  assert.ok(doc.querySelector('.requirement-card').textContent.includes('DOM reviewer'));
  assert.ok(doc.querySelector('#tz-status').textContent.includes('TZ_SOURCE_NOT_BOUND'));
  dom.window.close();dom=await open();doc=dom.window.document;
  await until(()=>doc.querySelectorAll('nav .session').length===2);
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Проверь высоту по ТЗ').click();
  await until(()=>doc.querySelector('.requirement-card')?.textContent.includes('SOURCE_LINKED'));
  const editing=doc.querySelector('.requirement-conclusion');editing.value='Черновик до проверки';editing.dispatchEvent(new dom.window.Event('input',{bubbles:true}));editing.focus();editing.setSelectionRange(2,5);
  const history=doc.querySelector('.requirement-card details');history.open=true;
  await new Promise(resolve=>setTimeout(resolve,2000));
  assert.ok(doc.activeElement.classList.contains('requirement-conclusion'),'Polling must preserve focused assessment control');
  assert.equal(doc.activeElement.selectionStart,2);assert.equal(doc.activeElement.selectionEnd,5);assert.equal(doc.activeElement.value,'Черновик до проверки');
  assert.equal(doc.querySelector('.requirement-card details').open,true,'Polling must preserve expanded assessment history');
  assert.ok(doc.querySelector('#drive-form'),'Drive import form missing');
  await until(()=>doc.querySelector('#drive-status').textContent.includes('не настроен'));
  assert.equal(doc.querySelector('#drive-import').disabled,true,'Missing OAuth must not be shown as connected');
  assert.equal(doc.querySelectorAll('.file').length,6,'Unavailable Drive must not manufacture an imported file (including two domain fixtures)');
  assert.ok(doc.querySelector('#real-case-panel'),'Stage-7 real case panel missing');
  await until(()=>[...doc.querySelector('#real-case-form select').options].some(o=>o.value));
  const caseSelect=doc.querySelector('#real-case-form select');caseSelect.value=[...caseSelect.options].find(o=>o.value).value;
  caseSelect.dispatchEvent(new dom.window.Event('change'));
  const roleChecks=[...doc.querySelectorAll('#case-source-roles input[data-case-role="TOR"]')];
  assert.equal(roleChecks.length,1,'Only files selected in CORE_RUN may be assigned');
  roleChecks[0].checked=true;
  doc.querySelector('#case-source-roles input[data-case-role="REPORT"]').checked=true;
  await new Promise(resolve=>setTimeout(resolve,1700));
  assert.equal(doc.querySelector('#case-source-roles input[data-case-role="TOR"]').checked,true,'Polling must preserve role selection');
  doc.querySelector('#real-case-form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('.real-case-result'));
  await until(()=>!doc.querySelector('#send').disabled);
  assert.ok(doc.querySelector('.real-case-result').textContent.includes('FINAL AUDIT NOT_RUN'));
  assert.ok(doc.querySelector('.real-case-result').textContent.includes('Кейс #1'));
  const caseReport=await (await fetch(origin+`/api/sessions/${id}/real-case`,{headers:{'X-Engineer-Token':token}})).json();
  assert.deepEqual(Object.keys(caseReport.cases[0].source_manifest).sort(),['REPORT','TOR'],'Role form must persist a manifest without JSON');
  assert.ok(doc.querySelector('#final-audit-panel'),'Stage-8 FINAL AUDIT panel missing');
  doc.querySelector('#project-next').click();
  assert.equal(doc.querySelector('#final-audit-panel').open,true,'Next audit action must reveal final audit controls');
  doc.querySelector('#final-audit-run').click();
  await until(()=>doc.querySelector('.final-audit-result'));
  await until(()=>!doc.querySelector('#send').disabled);
  assert.ok(doc.querySelector('.final-audit-result').textContent.includes('FINAL AUDIT COMPLETED'));
  assert.ok(doc.querySelector('.final-audit-result').textContent.includes('NOT ACCEPTED'));
  assert.ok(doc.querySelector('.final-audit-result').textContent.includes('BLOCK'));
  doc.querySelector('#tz-text').value='Новая версия ТЗ после аудита';
  doc.querySelector('#tz-form').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await until(()=>doc.querySelector('#project-next').textContent.includes('Обновить снимок'));
  assert.ok(doc.querySelector('#project-state').textContent.includes('устарел'),'Stale audit must direct rebuilding, not imply current decision');
  dom.window.renderRoute({jobs:[],files:[]},{requirements:[]},{cases:[]},{audits:[{current:true,fresh:true,effective_decision:'ACCEPTED',effective_acceptance_granted:true}]});
  assert.ok(doc.querySelector('#project-next').textContent.includes('Посмотреть решение'),'Accepted fixture should show a decision, not imaginary blockers');
  doc.querySelector('[data-stage="history"]').click();
  await until(()=>doc.querySelector('#history-records .history-record'));
  assert.ok(doc.querySelector('#history-panel').open,'History route must reveal archived records');
  doc.querySelector('#history-kind').value='jobs';
  doc.querySelector('#history-kind').dispatchEvent(new dom.window.Event('change'));
  await until(()=>doc.querySelector('#history-records .job'));
  assert.ok(doc.querySelector('#history-records').textContent.includes('Проверь высоту по ТЗ'));
  [...doc.querySelectorAll('nav .session')].find(b=>b.textContent==='Новый диалог').click();
  await until(()=>doc.querySelector('#title').textContent==='Новый диалог');
  assert.equal(doc.querySelector('#history-records').children.length,0,'Archive must not leak across projects');
  assert.equal(errors.length,0,errors.join('\n'));console.log(JSON.stringify({result:'PASS',dom_emulation:true,browser_visual_check:false,synthetic_model:true,real_ollama:false,checks:['launcher','background-worker','upload-action','source-context','chat','inert-markup','history-reload','session-switch','core-plan-no-model','core-plan-reload','evidence-register','inert-evidence','evidence-reload','evidence-draft-isolation','source-preview','preview-isolation','source-review','review-draft-poll','review-isolation','core-run-three-roles','core-run-inert-output','core-run-history-reload','drive-unconfigured','no-fabricated-import','file-extraction-coverage','pdf-page-coverage','automatic-pdf-analysis','advanced-document-actions','analysis-receipts'],requests:requests.length}));
 }finally{
  if(dom)dom.window.close();if(child){child.kill('SIGINT');await new Promise(resolve=>{if(child.exitCode!==null)return resolve();const t=setTimeout(()=>{child.kill('SIGKILL');resolve();},2500);child.once('exit',()=>{clearTimeout(t);resolve();});});}
  await new Promise(resolve=>model.close(resolve));fs.rmSync(temp,{recursive:true,force:true});
 }
})().catch(e=>{console.error(e);process.exitCode=1;});
